polkadot-live/polkadot-live-app

- src/controller/renderer/APIsController.ts
- src/controller/renderer/AccountsController.ts
- src/controller/renderer/SubscriptionsController.ts
- src/model/Account.ts
- src/model/Api.ts
- src/model/QueryMultiWrapper.ts
- src/orchestrators/TaskOrchestrator.ts
- src/orchestrators/TaskQueue.ts
- src/renderer/callbacks/index.ts
- src/renderer/callbacks/nominating.ts
- src/renderer/contexts/Subscriptions/index.tsx
- src/renderer/hooks/useInitIpcHandlers.ts
- src/renderer/library/Header/index.tsx
- src/renderer/screens/Home/Manage/Wrappers.tsx
- src/renderer/screens/Home/Manage/index.tsx
- src/types/accounts.ts
- src/utils/AccountUtils.ts
Callback now only executes when the network starts a new era that hasn't been checked for the respective account's exposure.
The callback algorithm has been re-implemented to fetch potentially new nominated validators for the respective account. The callback now only executes when the network starts a new era that has not yet been checked for the respective account's nominations. Overview of the new algorithm:
- Fetch live nominations for the account.
- Check any validators that the account was nominating before for commission changes.
- Get commissions for any new nominated validators in this era.
- Re-cache validator information for the account if anything has changed.
- Combine the commission change data for the event and notification.
A scrollbar is dynamically rendered when …
> fix: application debugging iteration

- README.md
- src/config/subscriptions/account.ts
- src/model/QueryMultiWrapper.ts
The `dataIndex` property is kept intact for a given task when its native checkbox is clicked.
> fix: debugging subscriptions

- src/renderer/library/Hardware/HardwareAddress/Wrapper.ts
- src/renderer/library/Hardware/HardwareAddress/index.tsx
- src/renderer/screens/Action/SignOverlay.tsx
- src/renderer/screens/Action/Wrappers.ts
- src/renderer/screens/Home/Manage/Accounts.tsx
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/renderer/screens/Home/Manage/Wrappers.tsx
- src/renderer/screens/Import/Ledger/Manage.tsx
- src/renderer/screens/Import/ReadOnly/Manage.tsx
- src/renderer/screens/Import/Vault/Manage.tsx
- src/renderer/screens/Import/Vault/Reader.tsx
- src/renderer/utils/ImportUtils.ts
Accordion headers now have a dynamic caret that will point right when the accordion item is collapsed, and down when it's open.
The QR code scanner's video size has been increased to make use of the available screen real-estate. The video is rendered within an overlay, and appears in the process of importing an account or signing a transaction with the vault app.
Imported addresses are categorised by chain ID in the order `Polkadot`, `Kusama` and `Westend`. They are then rendered in alphabetical order based on the its given name.
> feat: ui tasks

- src/renderer/library/Hardware/HardwareAddress/Wrapper.ts
- src/renderer/library/Hardware/HardwareAddress/index.tsx
- src/renderer/library/Hardware/HardwareAddress/types.ts
- src/renderer/screens/Home/Manage/Accounts.tsx
- src/renderer/screens/Home/Manage/Wrappers.tsx
- src/renderer/screens/Import/Addresses/Wrappers.tsx
- src/renderer/screens/Import/Addresses/types.ts
- src/renderer/screens/Import/Ledger/Address.tsx
- src/renderer/screens/Import/Ledger/Manage.tsx
- src/renderer/screens/Import/ReadOnly/Address.tsx
- src/renderer/screens/Import/ReadOnly/Manage.tsx
- src/renderer/screens/Import/Vault/Address.tsx
- src/renderer/screens/Import/Vault/Manage.tsx
- src/renderer/screens/Import/Wrappers.ts
- src/renderer/screens/Import/types.ts
- src/renderer/utils/ImportUtils.ts
This PR improves the import window's account listing UX.
- The priority of chain rendering is in the order `Polkadot`, `Kusama`, `Westend`.
- Accounts are listed alphabetically according to their associated name.
> feat: accounts list iteration

- src/config/processes/main.ts
- src/controller/main/WindowsController.ts
- src/main.ts
- src/preload.ts
- src/renderer/contexts/settings/SettingFlags/defaults.ts
- src/renderer/contexts/settings/SettingFlags/index.tsx
- src/renderer/contexts/settings/SettingFlags/types.ts
- src/renderer/hooks/useMessagePorts.ts
- src/renderer/screens/Settings/types.ts
- src/types/preload.ts
- src/utils/WindowUtils.ts
This PR implements a `Show on all workspaces` setting in the settings window.
When toggled on, the app will render its windows in all workspaces. When off, the app will only render in a single (active) workspace.
> feat: show on all workspaces setting

- src/controller/renderer/APIsController.ts
- src/model/Api.ts
- src/renderer/screens/Home/Events/Item.tsx
- src/renderer/screens/Home/Events/index.tsx
- src/renderer/screens/Home/Manage/Accounts.tsx
The click handler has been defined on the parent icon container to catch every click in the dismiss icon's region.
This component was being rendered in each accordion item if no accounts were imported. Fixed to only render once outside of the accordion when no accounts are imported.
Previously an error would be thrown if a requested API instance was in `'connecting'` status, and another part of the application requested that instance. Now, the subsequent API instance request waits until the instance is fully connected before receiving it.
> chore: debugging iteration

- package.json
- src/renderer/library/Footer/index.tsx
- src/renderer/library/Header/Wrapper.ts
- src/renderer/library/Header/index.tsx
- src/renderer/library/Menu/Wrapper.tsx
- src/renderer/library/Menu/index.tsx
- yarn.lock
- Hover effect on window drag area. 
Cannot add a hover effect on an element with `-webkit-app-region: drag;`.
> chore: header styling iteration

- src/config/help.ts
- src/config/processes/main.ts
- src/main.ts
- src/model/Account.ts
- src/preload.ts
- src/renderer/Providers.tsx
- src/renderer/contexts/import/AccountStatuses/index.tsx
- src/renderer/contexts/import/Addresses/defaults.ts
- src/renderer/contexts/import/Addresses/index.tsx
- src/renderer/contexts/import/Addresses/types.ts
- src/renderer/contexts/settings/SettingFlags/defaults.ts
- src/renderer/contexts/settings/SettingFlags/index.tsx
- src/renderer/contexts/settings/SettingFlags/types.ts
- src/renderer/hooks/useMessagePorts.ts
- src/renderer/library/Hardware/HardwareAddress/index.tsx
- src/renderer/screens/Import/Ledger/index.tsx
- src/renderer/screens/Import/ReadOnly/index.tsx
- src/renderer/screens/Import/Vault/index.tsx
- src/renderer/screens/Settings/Setting.tsx
- src/types/accounts.ts
- src/types/preload.ts
Initial implementation of the settings window `Import` and `Export` buttons.
When the `Export` button is clicked, the user can save their vault and read-only account data to a text file to a location on their disk. This data file will comprise of stringified JSON that represents the user's vault and read-only addresses they've added in Polkadot Live.
When the `Import` button is clicked, the user can select a text file previously exported from Polkadot Live. The application will read the data file and parse the stringified JSON into account objects. From there, these objects will be used to add the addresses to local storage and the import window's address state.
- If an address in an exported data file is already imported in Polkadot Live, it is skipped during the import process. This …
> feat: export and import account data

- src/renderer/contexts/import/Addresses/index.tsx
- src/renderer/contexts/import/Addresses/types.ts
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/Import/Addresses/Confirm.tsx
- src/renderer/screens/Import/ReadOnly/Manage.tsx
- src/renderer/screens/Import/Vault/Reader.tsx
- src/types/accounts.ts
Serialises and parses the `LocalAddress` type instead of the `AccountJson` type when exporting and importing addresses. This type change simplifies some logic and integrates more nicely with the import window.
> chore: data backup iteration

- src/renderer/callbacks/index.ts
- src/renderer/contexts/openGov/Treasury/default.ts
- src/renderer/contexts/openGov/Treasury/index.tsx
- src/renderer/contexts/openGov/Treasury/types.ts
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/OpenGov/Referenda/index.tsx
- src/renderer/screens/OpenGov/Tracks/index.tsx
- src/renderer/screens/OpenGov/Wrappers.ts
- src/renderer/screens/OpenGov/index.tsx
- src/renderer/utils/common.tsx
- src/utils/AccountUtils.ts
> feat: open gov ui additions

- src/config/subscriptions/interval.ts
- src/controller/renderer/IntervalsController.ts
- src/renderer/Providers.tsx
- src/renderer/contexts/main/IntervalSubscriptions/defaults.ts
- src/renderer/contexts/main/IntervalSubscriptions/index.tsx
- src/renderer/contexts/main/IntervalSubscriptions/types.ts
- src/renderer/contexts/main/Manage/defaults.ts
- src/renderer/contexts/main/Manage/index.tsx
- src/renderer/contexts/main/Manage/types.ts
- src/renderer/contexts/openGov/ReferendaSubscriptions/index.tsx
- src/renderer/contexts/openGov/ReferendaSubscriptions/types.ts
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/Home/Manage/Accounts.tsx
- src/renderer/screens/Home/Manage/IntervalRow.tsx
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/renderer/screens/Home/Manage/provider.tsx
- src/renderer/screens/Home/NoAccounts.tsx
- src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
- src/renderer/screens/OpenGov/Referenda/index.tsx
- src/renderer/screens/OpenGov/types.ts
- src/types/subscriptions.ts
This PR renders OpenGov referenda subscription tasks that have been added via the OpenGov window.
Controls on added OpenGov subscriptions are still static and are not yet hooked up to the system. The subscription toggle switch, one-shot button, and native OS notification checkbox, will be hooked up in the next PR.
> feat: render open gov subscriptions under manage tab 

- src/controller/renderer/IntervalsController.ts
- src/main.ts
- src/preload.ts
- src/renderer/contexts/main/Bootstrapping/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/hooks/useOpenGovMessagePorts.ts
- src/renderer/library/Header/index.tsx
- src/renderer/screens/OpenGov/utils.ts
- src/types/preload.ts
This PR persists and removes interval tasks from the Electron store when the `Add` and `Remove` buttons are clicked in the OpenGov window.
Persisted interval tasks are fetched when the app is launched to set React state and restore interval subscriptions from the previous time the app was used.
> feat: persist interval subscriptions

- src/renderer/screens/Home/Manage/IntervalRow.tsx
- src/renderer/screens/Home/Manage/Permissions.tsx
A "global" toggle is added to each OpenGov referendum accordion header to toggle all of its subscriptions on or off.
> feat: referenda global subscriptions toggle

- src/config/subscriptions/interval.ts
- src/controller/renderer/EventsController.ts
- src/controller/renderer/IntervalsController.ts
- src/controller/renderer/NotificationsController.ts
- src/main.ts
- src/renderer/callbacks/intervaled.ts
- src/renderer/contexts/main/Bootstrapping/index.tsx
- src/renderer/contexts/main/IntervalSubscriptions/index.tsx
- src/renderer/contexts/main/IntervalSubscriptions/types.ts
- src/renderer/contexts/main/Manage/index.tsx
- src/renderer/contexts/main/Manage/types.ts
- src/renderer/contexts/openGov/ReferendaSubscriptions/index.tsx
- src/renderer/contexts/openGov/ReferendaSubscriptions/types.ts
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/hooks/useOpenGovMessagePorts.ts
- src/renderer/screens/Home/Manage/IntervalRow.tsx
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
- src/types/subscriptions.ts
Adds methods in the intervals controller for processing (inserting or removing) an array of `IntervalSubscription` objects. Called when fetching persisted tasks from the store on app initialisation, or when clicking the "global" toggle to turn on or off all subscriptions for a referendum.
An intervals controller optimisation.
> chore: inserting and removing batched interval tasks

- src/renderer/contexts/openGov/Referenda/defaults.ts
- src/renderer/contexts/openGov/Referenda/index.tsx
- src/renderer/contexts/openGov/Referenda/types.ts
- src/renderer/contexts/openGov/Tracks/defaults.ts
- src/renderer/contexts/openGov/Tracks/index.tsx
- src/renderer/contexts/openGov/Tracks/types.ts
- src/renderer/contexts/openGov/Treasury/default.ts
- src/renderer/contexts/openGov/Treasury/index.tsx
- src/renderer/contexts/openGov/Treasury/types.ts
- src/renderer/hooks/useOpenGovMessagePorts.ts
- src/renderer/screens/OpenGov/Referenda/index.tsx
- src/renderer/screens/OpenGov/Tracks/index.tsx
- src/renderer/screens/OpenGov/index.tsx
- src/renderer/screens/OpenGov/types.ts
- src/renderer/utils/common.tsx
> chore: limit fetching open gov data + refresh data buttons

- src/config/help.ts
- src/config/processes/main.ts
- src/config/processes/renderer.ts
- src/config/settings.ts
- src/main.ts
- src/renderer/contexts/common/Help/types.ts
- src/renderer/contexts/main/AppSettings/defaults.ts
- src/renderer/contexts/main/AppSettings/index.tsx
- src/renderer/contexts/main/AppSettings/types.ts
- src/renderer/contexts/settings/SettingFlags/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/Settings/index.tsx
- src/renderer/screens/Settings/types.ts
This PR implements an `Enable Automatic Subscriptions` setting which is enabled by default.
When turned on, all possible subscriptions will be turned on for an account after it is imported.
When turned off, no subscriptions will be turned on after an account is imported.
> feat: automatically subscribe setting

- src/config/help.ts
- src/config/processes/main.ts
- src/config/settings.ts
- src/main.ts
- src/renderer/contexts/common/Help/types.ts
- src/renderer/contexts/main/AppSettings/defaults.ts
- src/renderer/contexts/main/AppSettings/index.tsx
- src/renderer/contexts/main/AppSettings/types.ts
- src/renderer/contexts/openGov/Polkassembly/index.tsx
- src/renderer/contexts/openGov/Polkassembly/types.ts
- src/renderer/contexts/openGov/Referenda/index.tsx
- src/renderer/contexts/settings/SettingFlags/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/library/Accordion/types.ts
- src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
- src/renderer/screens/OpenGov/Referenda/index.tsx
- src/renderer/screens/Settings/index.tsx
- src/renderer/screens/Settings/types.ts
This PR adds an app setting called `Enable Polkassembly Data`. 
When this setting is turned on, Polkadot Live uses the Polkassembly API to fetch proposal metadata, such as titles and descriptions of proposals.
When this setting is turned off, no such proposal metadata will be retrieved, and referenda will be listed with less information.
Users may prefer to turn this setting off to speed up fetching referenda, or not use a centralised API.
> feat: polkassembly api toggle setting

- src/renderer/contexts/openGov/Referenda/index.tsx
- src/renderer/screens/OpenGov/Referenda/InfoOverlay.tsx
- src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
- src/renderer/screens/OpenGov/Referenda/Wrappers.ts
- src/renderer/screens/OpenGov/Referenda/index.tsx
Initial implementation of an overlay that displays a referendum's title and description in raw text format.
This overlay is opened after clicking the `More` button for a referendum when the Polkassembly API is enabled.
> feat: referenda info overlay

- package.json
- src/config/help.ts
- src/config/processes/main.ts
- src/config/settings.ts
- src/main.ts
- src/renderer/Providers.tsx
- src/renderer/contexts/common/Help/types.ts
- src/renderer/contexts/main/AppSettings/defaults.ts
- src/renderer/contexts/main/AppSettings/index.tsx
- src/renderer/contexts/main/AppSettings/types.ts
- src/renderer/contexts/openGov/Polkassembly/axios.ts
- src/renderer/contexts/openGov/Polkassembly/defaults.ts
- src/renderer/contexts/openGov/Polkassembly/index.tsx
- src/renderer/contexts/openGov/Polkassembly/types.ts
- src/renderer/contexts/openGov/Referenda/defaults.ts
- src/renderer/contexts/openGov/Referenda/index.tsx
- src/renderer/contexts/openGov/Referenda/types.ts
- src/renderer/contexts/settings/SettingFlags/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/hooks/useOpenGovMessagePorts.ts
- src/renderer/library/Accordion/types.ts
- src/renderer/screens/OpenGov/Referenda/InfoOverlay.tsx
- src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
- src/renderer/screens/OpenGov/Referenda/Wrappers.ts
- src/renderer/screens/OpenGov/Referenda/index.tsx
- src/renderer/screens/Settings/index.tsx
- src/renderer/screens/Settings/types.ts
- src/renderer/theme/utils.scss
- yarn.lock
This PR integrates the Polkassembly API into the OpenGov window to fetch proposal metadata. This metadata includes off-chain information about submitted referenda, such as its title and description.
The settings window includes a new switch labeled `Enable Polkassembly Data`, which allows users to turn on and off usage of the Polkassembly API. The app fetches proposal data faster if the switch is turned off and the Polkassembly API is not being used. On the other hand, the Polkassembly API is required to render proposal titles and descriptions - data that is not stored on-chain. 
With the Polkassembly API enabled, the user is able to click a `More` button for listed referenda. When clicked, an overlay renders the referendum's full title and description in a raw text format. The overlay is …
> feat: polkassembly api integration

- src/renderer/screens/Home/Events/Item.tsx
- src/renderer/screens/Home/Events/Wrappers.tsx
- Primary actions are shown by default if they exist for an event item.
- If an event item doesn't have any primary actions but has secondary action buttons, the actions container is collapsed and secondary actions (links) are shown when it's expanded.
- Buttons to transition between showing primary and secondary buttons are rendered if necessary.
> chore: action items ui iteration

- src/config/help.ts
- src/config/processes/main.ts
- src/config/processes/renderer.ts
- src/config/settings.ts
- src/controller/main/EventsController.ts
- src/main.ts
- src/renderer/contexts/common/Help/types.ts
- src/renderer/contexts/main/AppSettings/defaults.ts
- src/renderer/contexts/main/AppSettings/index.tsx
- src/renderer/contexts/main/AppSettings/types.ts
- src/renderer/contexts/main/Events/index.tsx
- src/renderer/contexts/settings/SettingFlags/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/Home/Events/Wrappers.tsx
- src/renderer/screens/Home/index.tsx
- src/renderer/screens/Settings/types.ts
- src/utils/EventUtils.ts
This PR refactors the filtering logic when determining outdated events, and implements a new `Keep Outdated Events` setting.
When a new event is received by the main process, it firstly checks if any old event items of the subscription in question need removing. For example, when a new event item for the **Nomination Pool Rewards**  subscription is received, old event items for this subscription are removed (cleared from storage and the UI). The end result in this case is that the user will only be able to see the most recent event item on the UI.
However, certain users may wish to keep old event items in order to track past data. A new setting labelled `Keep Outdated Events` has been added to address this issue.
With the setting enabled, old event items will remain in the UI and managed …
> chore: setting to keep or remove outdated events

- package.json
- yarn.lock
Bump Electron to the most stable release at version 30.x.y.
> chore: bump electron to 30.1.2

- src/main.ts
- src/utils/WindowUtils.ts
The default Electron menu is only shown when the app is built with the `DEBUG` env variable defined. Otherwise, the application menu is set to `null`.
Example command for building the app in debug mode:
```
DEBUG=main:* yarn dev
```
> fix: remove default app menu

- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/library/Menu/index.tsx
- src/renderer/screens/Home/Wrappers.ts
- src/renderer/screens/Home/index.tsx
- src/renderer/screens/OpenGov/Wrappers.ts
- src/renderer/screens/OpenGov/index.tsx
- When fetching active referenda, referenda that are still in their prepare period are discarded. The goal of the referenda window is to currently list ongoing referenda that are in the decision period.
- Render chain icon in background of OpenGov window home buttons.
- Disable main window's cog menu when app is initially loading.
> fix: referenda debugging

- .github/workflows/release.yml
- entitlements/default.darwin.plist
- entitlements/extendedInfo.plist
- forge.config.ts
- package.json
- src/config/processes/main.ts
- src/main.ts
- src/utils/MenuUtils.ts
- src/utils/WindowUtils.ts
- yarn.lock
CI setup for distributing Mac OS distributable with tagged releases.
- GitHub actions workflow which currently publishes Mac OS distributable artefacts to the latest tagged release, targeting ARM64 (Apple Silicon) architectures.
- This workflow has to be triggered manually (`on: workflow_dispatch`) when a new tagged release is published to the repository.
Mac OS distributable artefacts are code signed and notarised, meaning they can be opened and run on Mac OS systems without any security warnings.
Some quick fixes have been implemented for some bugs that occurred for the release build:
Bug occurred if no menu bounds data had been persisted to the store.
The `LSBackgroundOnly` key is set in the app's `info.plist` to initially hide the dock icon. However, the dock icon re-appears when a …
> feat(ci): mac os release infra

- src/config/settings.ts
- src/main.ts
- src/preload.ts
- src/renderer/library/Footer/Wrapper.ts
- src/renderer/library/Header/Wrapper.ts
- src/renderer/library/Menu/Wrapper.tsx
- src/renderer/screens/Home/Manage/Accounts.tsx
- src/renderer/screens/Home/Wrappers.ts
- src/renderer/screens/Settings/index.tsx
- src/renderer/screens/Settings/types.ts
- src/types/preload.ts
- src/utils/WindowUtils.ts
- Settings to **Hide dock icon** and **Show on all workspaces** not displayed on Windows.  
- **macOS:** Position under tray icon.
- **Windows:** Snap to top-right corner of screen.
- Fix `z-index` values for header and footer.
- Make `<NoAccounts />` component colours more vibrant.
> fix: platform specifics

- src/renderer/screens/Home/Events/NoEvents.tsx
- src/renderer/screens/Home/Events/Wrappers.tsx
- src/renderer/screens/Home/Manage/Accounts.tsx
- src/renderer/screens/OpenGov/Referenda/index.tsx
- src/renderer/screens/OpenGov/Tracks/TrackRow.tsx
- src/renderer/screens/OpenGov/Tracks/Wrappers.ts
- src/renderer/screens/OpenGov/Tracks/index.tsx
- src/renderer/screens/OpenGov/index.tsx
- src/renderer/utils/common.tsx
- src/utils/WindowUtils.ts
The renderer's index file could not be loaded on Windows with the slash present. Omitting the slash successfully loads the renderer's content on Windows and macOS platforms.
```typescript
window.loadURL(`file://${path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html#/${route}`)}`);
```
```typescript
window.loadURL(`file://${path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html#${route}`)}`);
```
- Some miscellaneous polish and UI cleanup, including in the OpenGov window.
> fix: debugging polish iteration

- src/main.ts
- src/renderer/contexts/import/ImportHandler/index.tsx
- src/renderer/screens/Import/ReadOnly/Manage.tsx
- **Clear the Electron store when a new Polkadot Live version is opened for the first time.**
Doing this will prevent any compatibility issues between persisted data from previous versions and updated data structures in the newer version. A `TODO` has been added for implementing a data migration system between versions. 
- **Don't fetch account data on import if the app is offline.**
When a Vault or read only account is imported, the app will only fetch its data and send it to the main window if it's in online mode. This is because an internet connection is required to fetch the account's data.
> fix: debugging tasks

- src/controller/renderer/IntervalsController.ts
- src/renderer/Providers.tsx
- src/renderer/contexts/main/IntervalTasksManager/defaults.ts
- src/renderer/contexts/main/IntervalTasksManager/index.tsx
- src/renderer/contexts/main/IntervalTasksManager/types.ts
- src/renderer/contexts/main/Subscriptions/index.tsx
- src/renderer/contexts/main/Subscriptions/types.ts
- src/renderer/screens/Home/Manage/IntervalRow.tsx
- src/renderer/screens/Home/Manage/PermissionRow.tsx
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/renderer/screens/Home/Manage/types.tsx
- [chore: interval subscription manager context (#598)](https://github.com/polkadot-live/polkadot-live-app/pull/598)
Lifts interval subscription handler functions to a dedicated context.
- [fix: interval os notifications](https://github.com/polkadot-live/polkadot-live-app/pull/599)
Refine logic for determining how to render OS notifications for interval subscriptions.
> chore: subscription components optimisation

- src/renderer/contexts/main/Manage/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
Referenda with IDs of 1000 and above are received as a string with thousand-separated commas. This PR removes commas from received referenda IDs, parsing the data correctly.
> fix: referenda parsing

- src/config/help.ts
- src/renderer/kits/Icons/IconWarning/index.tsx
- src/renderer/screens/Home/Manage/PermissionRow.tsx
- Fix help overlay title for the free balance subscription.
- Render warning icon in the pending payouts subscription row.
- Informs user that the subscription callback could take over 10 seconds.
> chore: ui tweaks

- src/renderer/contexts/import/Addresses/defaults.ts
- src/renderer/contexts/import/Addresses/index.tsx
- src/renderer/contexts/import/Addresses/types.ts
- src/renderer/screens/Import/Ledger/index.tsx
- src/renderer/screens/Import/ReadOnly/Manage.tsx
- src/renderer/screens/Import/Vault/Reader.tsx
- Can no longer import an address that has already been imported via another import method.
> chore: account import iteration

- src/main.ts
- src/renderer/Providers.tsx
- src/renderer/contexts/import/AccountStatuses/index.tsx
- src/renderer/contexts/import/AddHandler/defaults.ts
- src/renderer/contexts/import/AddHandler/index.tsx
- src/renderer/contexts/import/AddHandler/types.ts
- src/renderer/library/Hardware/HardwareAddress/index.tsx
- src/renderer/library/Hardware/HardwareAddress/types.ts
- src/renderer/screens/Import/Addresses/Confirm.tsx
- src/renderer/screens/Import/Addresses/types.ts
- src/renderer/screens/Import/Ledger/Address.tsx
- src/renderer/screens/Import/Ledger/Manage.tsx
- src/renderer/screens/Import/ReadOnly/Address.tsx
- src/renderer/screens/Import/ReadOnly/Manage.tsx
- src/renderer/screens/Import/Vault/Address.tsx
- src/renderer/screens/Import/types.ts
- src/renderer/utils/ImportUtils.ts
- src/types/communication.ts
Handle renaming import window account data and updating its import flag in the Electron store. Local storage code has been removed  in the implementation.
> chore(accounts): rename + update in store

- src/config/help.ts
- src/config/subscriptions/account.ts
- src/controller/renderer/EventsController.ts
- src/controller/renderer/NotificationsController.ts
- src/model/QueryMultiWrapper.ts
- src/orchestrators/TaskOrchestrator.ts
- src/renderer/callbacks/index.ts
- src/renderer/callbacks/oneshots.ts
- src/renderer/contexts/common/Help/types.ts
- src/types/subscriptions.ts
- src/utils/EventUtils.ts
Initial implementation of the `nominating:nominations` subscription.
A notification is received when a user's nominated validator set changes on the start of a new era.
> feat(subscriptions): nominations changed subscription

- src/config/help.ts
- src/config/subscriptions/account.ts
- src/controller/renderer/EventsController.ts
- src/controller/renderer/NotificationsController.ts
- src/model/QueryMultiWrapper.ts
- src/renderer/callbacks/index.ts
- src/renderer/callbacks/nominating.ts
- src/renderer/callbacks/oneshots.ts
- src/renderer/screens/Home/Manage/PermissionRow.tsx
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/utils/EventUtils.ts
Replaces the pending payouts nominating subscription with a new `Era Rewards` subscription.
Get notified of your nominating rewards from the previous era (when a new era starts) with this new subscription.
> chore(subscriptions): fix nominating pending payouts

- src/main.ts
- src/preload.ts
- src/renderer/contexts/main/Bootstrapping/index.tsx
- src/renderer/contexts/main/IntervalTasksManager/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/types/communication.ts
- src/types/preload.ts
Refactor the preload API to handle interval tasks with a generic IPC message.
Simplifies the preload API and unifies interval task handling logic within the main process.
> chore: generic interval task ipcs

- src/controller/main/SubscriptionsController.ts
- src/controller/renderer/AccountsController.ts
- src/controller/renderer/SubscriptionsController.ts
- src/main.ts
- src/preload.ts
- src/renderer/contexts/main/Subscriptions/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/screens/Home/Manage/Permissions.tsx
- src/types/communication.ts
- src/types/preload.ts
Refactor the preload API to handle subscription tasks with a generic IPC message.
Simplifies the preload API and unifies subscription task handling logic within the main process.
> chore: generic subscription task ipcs

- src/controller/main/AccountsController.ts
- src/controller/renderer/AccountsController.ts
- src/main.ts
- src/preload.ts
- src/renderer/contexts/main/Addresses/defaults.ts
- src/renderer/contexts/main/Addresses/index.tsx
- src/renderer/contexts/main/Addresses/types.ts
- src/renderer/hooks/useMainMessagePorts.ts
- src/types/communication.ts
- src/types/preload.ts
Refactor the preload API to handle account tasks with a generic IPC message.
Simplifies the preload API and unifies account task handling logic within the main process.
> chore: account ipcs refactor 

- src/config/processes/main.ts
- src/controller/main/EventsController.ts
- src/controller/main/SettingsController.ts
- src/main.ts
- src/preload.ts
- src/renderer/contexts/main/AppSettings/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/types/communication.ts
- src/types/preload.ts
- src/utils/WindowUtils.ts
Refactor the preload API to handle settings tasks with a generic IPC message.
Simplifies the preload API and unifies settings task handling logic within the main process.
> chore: settings ipcs refactor

- src/controller/main/AddressesController.ts
- src/main.ts
- src/preload.ts
- src/renderer/contexts/import/ImportHandler/index.tsx
- src/renderer/contexts/main/Bootstrapping/index.tsx
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/library/Menu/index.tsx
- src/types/preload.ts
- src/utils/WindowUtils.ts
- Allows address to be persisted even if the import window is not open.
> fix: debugging iteration

- src/controller/main/AddressesController.ts
- src/controller/main/BackupController.ts
- src/controller/main/SubscriptionsController.ts
- src/controller/renderer/AccountsController.ts
- src/controller/renderer/SubscriptionsController.ts
- src/renderer/contexts/import/ImportHandler/index.tsx
- src/renderer/contexts/main/Addresses/index.tsx
- src/renderer/contexts/main/Addresses/types.ts
- src/renderer/contexts/main/Bootstrapping/index.tsx
- src/renderer/contexts/main/Manage/index.tsx
- src/renderer/hooks/useImportMessagePorts.ts
- src/renderer/hooks/useMainMessagePorts.ts
- src/renderer/utils/ImportUtils.ts
- src/types/accounts.ts
- src/types/communication.ts
Augments the backup system by implementing the exporting and importing of account subscriptions.
- Data from the backup file takes precedence.
[feat: export account subscriptions #708](https://github.com/polkadot-live/polkadot-live-app/pull/708)
[feat: import account subscriptions #709](https://github.com/polkadot-live/polkadot-live-app/pull/709)
> feat: account subscriptions backup

- src/controller/main/SettingsController.ts
- src/renderer/Providers.tsx
- src/renderer/contexts/main/AppSettings/defaults.ts
- src/renderer/contexts/main/AppSettings/index.tsx
- src/renderer/contexts/main/AppSettings/types.ts
- src/renderer/library/SideNav/SideNav.tsx
- src/renderer/library/contexts/SideNavContext/defaults.ts
- src/renderer/library/contexts/SideNavContext/index.tsx
- src/renderer/library/contexts/SideNavContext/types.ts
- src/renderer/screens/Settings/types.ts
The flag that controls whether the side nav bar is collapsed or expanded is persisted to the store.
The side nav's collapsed state will be restored when the app is relaunched.
> feat: persist side nav collapsed state

- packages/renderer/src/config/settings.ts
- packages/renderer/src/renderer/screens/Home/index.tsx
- packages/ui/src/components/Header/index.tsx
- packages/ui/src/components/Header/types.ts
Electron's `win.setMovable(movable)` method works on macOS and Windows only.
With this in mind, docking won't work as expected on Linux systems. Therefore, the dock button is not currently displayed on Linux environments.
It is possible to move and resize windows on Linux. A future PR could implement a UI presenting "docking" options on Linux platforms to align with the Mac and Windows versions.
> chore: dynamic dock button

- packages/main/src/utils/WindowUtils.ts
Graphical glitch occurred when programatically hiding the base window immediately after creating it.
Fixed by setting the `BrowserWindow` constructor's `show` option to `false` on creation.
> fix: linux base window glitch

- packages/ui/src/components/Header/index.tsx
- packages/ui/src/components/Padlock/Wrapper.ts
- packages/ui/src/components/Padlock/index.tsx
- packages/ui/src/components/Padlock/types.ts
- packages/ui/src/components/index.ts
Replace the header's `Dock` button in the main window's header with an animated padlock icon.
This refactor makes the header design consistent between Linux, Mac and Windows versions of Polkadot Live.
> feat: header dock toggle icon

- packages/main/src/controller/ExtrinsicsController.ts
- packages/renderer/src/controller/ExtrinsicsController.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/types/src/communication.ts
- packages/types/src/preload.ts
When the Extrinsics window is opened, persisted extrinsics in the store are fetched and rendered in the window.
> feat: fetch stored extrinsics

- packages/main/src/controller/ExtrinsicsController.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
- packages/renderer/src/renderer/hooks/useActionMessagePorts.ts
- packages/renderer/src/renderer/screens/Action/index.tsx
- packages/types/src/communication.ts
- packages/types/src/tx.ts
Stored extrinsics are updated when their status changes.
> feat: update persisted extrinsics

- packages/main/src/controller/SettingsController.ts
- packages/renderer/src/config/help.ts
- packages/renderer/src/config/settings.ts
- packages/renderer/src/controller/ExtrinsicsController.ts
- packages/renderer/src/renderer/contexts/main/AppSettings/defaults.ts
- packages/renderer/src/renderer/contexts/main/AppSettings/index.tsx
- packages/renderer/src/renderer/contexts/main/AppSettings/types.ts
- packages/renderer/src/renderer/contexts/settings/SettingFlags/index.tsx
- packages/renderer/src/renderer/contexts/settings/SettingFlags/types.ts
- packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
- packages/renderer/src/renderer/screens/Settings/Setting.tsx
- packages/renderer/src/renderer/screens/Settings/index.tsx
- packages/renderer/src/renderer/screens/Settings/types.ts
- packages/types/src/help.ts
- packages/types/src/settings.ts
New extrinsics setting in Settings window labelled **Silence OS Notifications for Extrinsics**.
A native OS notification will not be shown during an extrinsic submission if either of the following settings are enabled:
- **Extrinscs --> Silence OS Notifications for Extrinsics**
- **General --> Silence OS Notifications**
> feat: toggle extrinsics os notifications setting

- packages/main/src/controller/AddressesController.ts
- packages/renderer/src/renderer/screens/Home/Send/Wrappers.ts
- packages/renderer/src/renderer/screens/Home/Send/index.tsx
- packages/renderer/src/renderer/screens/Home/Send/types.ts
- packages/types/src/communication.ts
Implements dynamic state for the send screen and most of its intended behaviour.
The screen still requires some blockchain queries and copy-address functionality, which will be implemented in the next PRs.
> feat: dynamic send screen

- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/screens/Home/Send/index.tsx
- packages/ui/src/components/TooltipRx/TooltipRx.tsx
- packages/ui/src/components/TooltipRx/types.ts
- packages/ui/src/utils/index.ts
- packages/ui/src/utils/toast.tsx
UX improvements when copying an address.
The tooltip remains open and its text changes to `Copied!` when the copy address button is clicked.
The `renderToast` utility has been moved to the `ui` package.
> chore: copy address button polish

- packages/renderer/src/controller/ExtrinsicsController.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/screens/Action/TxActionItem.tsx
- packages/renderer/src/renderer/screens/Home/Send/SendHelpers.tsx
- packages/renderer/src/renderer/screens/Home/Send/Wrappers.ts
- packages/renderer/src/renderer/screens/Home/Send/index.tsx
- packages/renderer/src/utils/AccountUtils.ts
- packages/types/src/tx.ts
Fetches a sender account's current spendable balance and improves the send screen UX.
Upon clicking `Proceed`, a new extrinsic item is added to the Extrinsics window for signing.
> chore: send screen node interactions

- packages/renderer/src/controller/ExtrinsicsController.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
- packages/renderer/src/renderer/hooks/useActionMessagePorts.ts
- packages/renderer/src/renderer/screens/Action/Helpers.tsx
- packages/renderer/src/utils/AccountUtils.ts
Verifies an extrinsic is still valid when the sign button is clicked.
A error will be shown as a toast notification if an extrinsic is not longer valid. An extrinsic won't be valid if an account has insufficient balance, or if an account's nomination pool rewards have since changed.
> feat: verify extrinsics before signing

- packages/main/src/config/main.ts
- packages/main/src/main.ts
- packages/renderer/src/config/walletConnect.ts
- packages/renderer/src/renderer/Providers.tsx
- packages/renderer/src/renderer/contexts/common/Connections/defaults.ts
- packages/renderer/src/renderer/contexts/common/Connections/index.tsx
- packages/renderer/src/renderer/contexts/common/Connections/types.ts
- packages/renderer/src/renderer/contexts/import/WalletConnect/defaults.ts
- packages/renderer/src/renderer/contexts/import/WalletConnect/index.tsx
- packages/renderer/src/renderer/contexts/import/WalletConnect/types.ts
- packages/renderer/src/renderer/contexts/main/WalletConnect/defaults.ts
- packages/renderer/src/renderer/contexts/main/WalletConnect/index.tsx
- packages/renderer/src/renderer/contexts/main/WalletConnect/types.ts
- packages/renderer/src/renderer/hooks/useImportMessagePorts.ts
- packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
- packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
- packages/types/package.json
- packages/types/src/communication.ts
- packages/types/src/walletConnect.ts
In preparation for signing extrinsics with the WalletConnect protocol, the WalletConnect provider and session have been moved to a new context in the main renderer.
The import window's WalletConnect context communicates with the main renderer's new context to facilitate fetching addresses via a WalletConnect session.
- WalletConnect state flags re-implemented as relay flags which are accessible to the whole application
- WalletConnect import logic lifted to contexts and separated from markup
- WalletConnect constant data moved to a config file
> chore: move wallet connect context

- packages/renderer/src/renderer/screens/Action/Signer.tsx
- packages/renderer/src/renderer/screens/Action/index.tsx
Verify that an extrinsic is still valid when clicking an extrinsic item's dropdown menu `Sign` button.
> fix: verify extrinsic on dropdown sign

- packages/renderer/src/renderer/contexts/import/WalletConnectImport/defaults.ts
- packages/renderer/src/renderer/contexts/import/WalletConnectImport/index.tsx
- packages/renderer/src/renderer/contexts/import/WalletConnectImport/types.ts
- packages/renderer/src/renderer/contexts/main/WalletConnect/index.tsx
- packages/renderer/src/renderer/hooks/useImportMessagePorts.ts
When the user fetches WalletConnect addresses from the import window, the WalletConnect modal is opened over the import screen after the `Connect` button is clicked.
Messaging between the main and import renderers ensures the WalletConnect modal is configured, opened and closed correctly.
Opening the WalletConnect modal within the import window instead of the main window when importing addresses improves UX and keeps the user within a single window.
> chore: open wallet connect modal inside import window

- packages/main/src/controller/AddressesController.ts
- packages/main/src/controller/BackupController.ts
- packages/main/src/controller/ExtrinsicsController.ts
- packages/main/src/utils/ImportUtils.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
- packages/renderer/src/renderer/contexts/main/DataBackup/index.tsx
- packages/renderer/src/renderer/hooks/useActionMessagePorts.ts
- packages/renderer/src/renderer/screens/Action/ExtrinsicItemContent.tsx
- packages/renderer/src/renderer/screens/Action/Helpers.tsx
- packages/renderer/src/renderer/utils/ImportUtils.ts
- packages/types/src/communication.ts
Implementation of exporting extrinsics data to a backup file, and importing extrinsics backup data back into Polkdaot Live.
Account renames are synced with dynamic transaction data with cached account names.
> feat: backup extrinsics

- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/screens/Home/Manage/Accounts.tsx
- packages/renderer/src/renderer/screens/Home/Manage/Permissions.tsx
- packages/renderer/src/renderer/screens/Home/Manage/index.tsx
- packages/renderer/src/renderer/screens/Home/Manage/types.tsx
A couple of bug fixes.
- Handle the case when zero extrinsics are fetched from the store when loading the extrinsics window.
- The accordion that renders account subscriptions doesn't re-open when a category switch is clicked.
> fix: debugging

- packages/main/src/controller/ExtrinsicsController.ts
- packages/renderer/src/controller/ExtrinsicsController.ts
- packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
- packages/renderer/src/renderer/screens/Home/Send/index.tsx
Implements native token transfer limits while Polkadot Live is in alpha status:
- Transfer extrinsics supported on **Kusama** and **Westend** networks (Polkadot coming soon)
- Transfer a maximum of **100** native tokens
> feat: transfer network amount limits

- packages/main/src/config/main.ts
- packages/main/src/main.ts
- packages/preload/src/preload.ts
- packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
- packages/renderer/src/renderer/screens/Home/index.tsx
- packages/types/src/preload.ts
Displays the Polkadot Live disclaimer when the app is launched for the first time.
> chore: show disclaimer on initial launch

- packages/renderer/src/renderer/callbacks/intervaled.ts
- packages/renderer/src/renderer/contexts/openGov/Polkassembly/defaults.ts
- packages/renderer/src/renderer/contexts/openGov/Polkassembly/index.tsx
- packages/renderer/src/renderer/contexts/openGov/Polkassembly/types.ts
- packages/renderer/src/renderer/contexts/openGov/Referenda/defaults.ts
- packages/renderer/src/renderer/contexts/openGov/Referenda/index.tsx
- packages/renderer/src/renderer/contexts/openGov/Referenda/types.ts
- packages/renderer/src/renderer/contexts/openGov/ReferendaSubscriptions/index.tsx
- packages/renderer/src/renderer/contexts/openGov/ReferendaSubscriptions/types.ts
- packages/renderer/src/renderer/contexts/openGov/TaskHandler/index.tsx
- packages/renderer/src/renderer/contexts/openGov/TaskHandler/types.ts
- packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
- packages/renderer/src/renderer/hooks/useOpenGovMessagePorts.ts
- packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/index.tsx
- packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/types.ts
- packages/renderer/src/renderer/screens/OpenGov/Overview/OverviewExplore.tsx
- packages/renderer/src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
- packages/renderer/src/renderer/screens/OpenGov/Referenda/Wrappers.ts
- packages/renderer/src/renderer/screens/OpenGov/Referenda/index.tsx
- packages/renderer/src/renderer/screens/OpenGov/types.ts
- packages/renderer/src/renderer/utils/openGovUtils.ts
- packages/types/src/openGov.ts
Iteration on the OpenGov referenda infrastructure:
> feat: ongoing referenda iteration

- packages/renderer/src/controller/AccountsController.ts
- packages/renderer/src/controller/SubscriptionsController.ts
- packages/renderer/src/model/QueryMultiWrapper.ts
- packages/renderer/src/orchestrators/TaskOrchestrator.ts
- packages/renderer/src/renderer/contexts/main/Subscriptions/index.tsx
- packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
Separately functions for building an account's query multi argument, and actually running the query multi.
Allows building the full argument  before running the subscription.
> fix: batched task query building

- .github/CODEOWNERS
- package.json
- packages/renderer/src/renderer/callbacks/nominating.ts
- packages/ui/package.json
- scripts/electron-builder.config.prod.mjs
- yarn.lock
Batches queries under the hood to avoid running out of heap memory when processing hundreds of queries, particularly via the light client.
> chore: pre-release tasks

- .github/workflows/ci.yml
- check-markdown-links-config.json
- Updates the markdown link check GitHub action
- Adds an ignore pattern to disable checking GitHub compare URLs
> fix(ci): markdown link check

- packages/core/src/controllers/ExtrinsicsController.ts
- packages/renderer/src/hooks/useActionMessagePorts.ts
- packages/renderer/src/hooks/useMainMessagePorts.ts
- packages/types/src/tx.ts
The following code currently works in the development build but throws a `TypeError` exception in the production build:
```ts
const metadata = api.metadata;
const merkleizer = new MerkleizedMetadata(metadata, { decimals, tokenSymbol });
```
The production build expects the `metadata` argument to be of type `Uint8Array`. The following code is currently in place to ensure this:
```ts
import { $Metadata } from 'dedot/codecs';
const metadata = $Metadata.tryEncode(api.metadata);
const merkleizer = new MerkleizedMetadata(metadata, { decimals, tokenSymbol });
```
> fix(metadata): ensure Uint8Array input to MerkleizedMetadata

- packages/renderer/src/screens/Action/Dialogs/DialogExtrinsicSummary.tsx
Display the signing method in the transaction summary dialog.
> feat(ui): display sign method in transaction summary

- packages/core/src/controllers/ExtrinsicsController.ts
- packages/renderer/src/contexts/action/TxMeta/defaults.ts
- packages/renderer/src/contexts/action/TxMeta/index.tsx
- packages/renderer/src/contexts/action/TxMeta/types.ts
- packages/renderer/src/hooks/useActionMessagePorts.ts
- packages/types/src/tx.ts
Cache and persist the transaction hash when a submitted extrinsic is finalised on the network.
> feat(extrinsics): store and track transaction hash

- packages/renderer/src/screens/Action/Dropdowns/ExtrinsicDropdownMenu.tsx
- packages/renderer/src/screens/Action/Dropdowns/types.ts
- packages/renderer/src/screens/Action/index.tsx
Adds a "Block Explorer" link to the extrinsics menu.
The link is enabled once a transaction is finalised. Clicking it opens detailed extrinsic info in an external block explorer.
> feat(ui): integrate block explorer link for extrinsics

- packages/consts/src/walletConnect.ts
- packages/renderer/src/Providers.tsx
- packages/renderer/src/contexts/action/WcFeedback/defaults.ts
- packages/renderer/src/contexts/action/WcFeedback/index.tsx
- packages/renderer/src/contexts/action/WcFeedback/types.ts
- packages/renderer/src/contexts/action/index.ts
- packages/renderer/src/contexts/main/WalletConnect/index.tsx
- packages/renderer/src/contexts/main/WalletConnect/types.ts
- packages/renderer/src/hooks/useActionMessagePorts.ts
- packages/renderer/src/hooks/useMainMessagePorts.ts
- packages/renderer/src/screens/Action/Overlays/SignLedgerOverlay.tsx
- packages/renderer/src/screens/Action/Overlays/WcSignOverlay.tsx
- packages/types/src/ledger.ts
- packages/types/src/walletConnect.ts
- packages/ui/src/components/Cards/InfoCard.styles.ts
* Adds new error status codes and user-friendly feedback message.
> feat(ui): wallet connect signing feedback

- packages/renderer/src/contexts/import/RenameHandler/defaults.ts
- packages/renderer/src/contexts/import/RenameHandler/index.tsx
- packages/renderer/src/contexts/import/RenameHandler/types.ts
- packages/renderer/src/screens/Import/Addresses/Address.tsx
- packages/renderer/src/screens/Import/Addresses/Dialogs/DialogManageAccounts.tsx
- packages/renderer/src/screens/Import/Addresses/Dialogs/DialogShowAddress.tsx
- packages/renderer/src/screens/Import/Addresses/Dropdowns/DropdownAccount.tsx
- packages/renderer/src/screens/Import/Addresses/Listing.tsx
- packages/renderer/src/screens/Import/Ledger/Import/index.tsx
- packages/renderer/src/screens/Import/WalletConnect/Import/index.tsx
- packages/ui/src/components/Hardware/HardwareAddress/HardwareAddress.tsx
- packages/ui/src/components/ViewAddressIcon/ViewAddressIcon.styles.ts
- packages/ui/src/components/ViewAddressIcon/ViewAddressIcon.tsx
- packages/ui/src/components/ViewAddressIcon/index.ts
- packages/ui/src/components/index.ts
- packages/ui/src/styles/index.ts
Implements a reusable `ViewAddressIcon` component used to open a dialog to show a full address. This component has been added to fetched Ledger and WalletConnect account listings.
> feat(ui): show address dialog for fetched ledger and wallet connect accounts
