README.md
src/config/subscriptions/account.ts

Point to documentation repository from README.

chore: readme update

---

src/renderer/contexts/Subscriptions/defaults.ts
src/renderer/contexts/Subscriptions/index.tsx
src/renderer/contexts/Subscriptions/types.ts
src/renderer/library/Accordion/index.tsx
src/renderer/library/Switch/index.tsx
src/renderer/screens/Home/Manage/Accounts.tsx
src/renderer/screens/Home/Manage/PermissionRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx

Initial implementation of category toggles for instantly turning on or off all subscriptions in a given category.

feat: global category toggles for all tasks

---

package.json
src/config/processes/renderer.ts
src/renderer/callbacks/index.ts
src/renderer/library/Header/Wrapper.ts
src/renderer/library/Header/index.tsx
yarn.lock

Implements a switch in the header that acts as a global toggle to silences OS notifications.

feat: global silence notifications toggle

---

src/renderer/Wrappers.ts
src/renderer/kits/Overlay/index.scss
src/renderer/library/ActionItem/Wrapper.ts
src/renderer/library/Footer/Wrapper.ts
src/renderer/library/Hardware/HardwareAddress/Wrapper.ts
src/renderer/library/Hardware/HardwareStatusBar/Wrapper.ts
src/renderer/library/Header/Wrapper.ts
src/renderer/library/Header/index.tsx
src/renderer/library/Menu/Wrapper.tsx
src/renderer/screens/Action/Wrappers.ts
src/renderer/screens/Action/index.tsx
src/renderer/screens/Home/Events/Category.tsx
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/Home/Events/index.tsx
src/renderer/screens/Home/Events/types.ts
src/renderer/screens/Home/Manage/Accounts.tsx
src/renderer/screens/Home/Manage/PermissionRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/Home/Wrappers.ts
src/renderer/screens/Home/index.tsx
src/renderer/screens/Import/Addresses/Wrappers.tsx
src/renderer/screens/Import/Home.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/Ledger/Splash.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Manage.tsx
src/renderer/screens/Wrappers.ts
src/renderer/theme/theme.scss

Foundation for a new dark theme.

chore: theme refresh

---

package.json
src/renderer/library/Tooltip/Wrapper.ts
src/renderer/library/Tooltip/index.tsx
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/Home/Manage/PermissionRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/Home/Manage/types.tsx
yarn.lock

The one-shot button and checkbox to toggle OS notifications for subscription rows have been re-imagined as simple icons and a tooltip when the icon is hovered over.

feat: icons iteration for subscription rows

---

src/renderer/Providers.tsx
src/renderer/contexts/AccountStatuses/defaults.ts
src/renderer/contexts/AccountStatuses/index.tsx
src/renderer/contexts/AccountStatuses/types.ts
src/renderer/hooks/useMessagePorts.ts
src/renderer/library/Hardware/HardwareAddress/Wrapper.ts
src/renderer/library/Hardware/HardwareAddress/index.tsx
src/renderer/library/Hardware/HardwareAddress/types.ts
src/renderer/screens/Import/Addresses/Confirm.tsx
src/renderer/screens/Import/Addresses/types.ts
src/renderer/screens/Import/Ledger/Address.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/ReadOnly/Address.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Address.tsx
src/renderer/screens/Import/Vault/Manage.tsx
src/renderer/screens/Import/types.ts

Importing an account requires interaction with the blockchain network and could take several seconds depending on the internet connection speed.
This PR renders a 3-dot loading spinner inside the import button when an account is being imported.

feat: loading spinner rendered when importing an account

---

src/renderer/screens/Home/Events/Item.tsx
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/Home/Events/index.tsx

UI button added to event items with action buttons. The event item's action buttons are collapsed and expanded upon clicking the button.

feat: collapsible event item actions

---

src/config/processes/main.ts
src/main.ts
src/preload.ts
src/renderer/library/Header/Wrapper.ts
src/renderer/library/Header/index.tsx
src/types/preload.ts
src/utils/WindowUtils.ts

Implement window docking mode to render the main window as fixed under the app's tray icon.
The main window will not be movable or resizable when docked.
- In settings window have controls to increase or decrease main window height when docked.

feat: dock and un-dock main window

---

src/renderer/library/Hardware/HardwareAddress/Wrapper.ts
src/renderer/library/Hardware/HardwareAddress/index.tsx
src/renderer/library/Hardware/HardwareStatusBar/Wrapper.ts
src/renderer/library/Hardware/HardwareStatusBar/index.tsx
src/renderer/screens/Import/Addresses/Wrappers.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Manage.tsx

Improved styling of account listings in the import window.

chore: accounts list styling iteration

---

src/config/help.ts
src/config/processes/main.ts
src/config/processes/openGov.ts
src/config/processes/renderer.ts
src/main.ts
src/model/Track.ts
src/renderer/Providers.tsx
src/renderer/Router.tsx
src/renderer/contexts/common/Help/types.ts
src/renderer/contexts/openGov/Tracks/defaults.ts
src/renderer/contexts/openGov/Tracks/index.tsx
src/renderer/contexts/openGov/Tracks/types.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/hooks/useOpenGovMessagePorts.ts
src/renderer/library/Menu/index.tsx
src/renderer/screens/OpenGov/TrackRow.tsx
src/renderer/screens/OpenGov/Wrappers.ts
src/renderer/screens/OpenGov/index.tsx
src/renderer/screens/OpenGov/types.ts
src/renderer/screens/Wrappers.ts
src/types/communication.ts
src/utils/WindowUtils.ts

Implement OpenGov window boilerplate with origin & track information page.

feat: initial open gov window

---

src/config/help.ts
src/renderer/contexts/common/Help/types.ts
src/renderer/contexts/openGov/Tracks/defaults.ts
src/renderer/contexts/openGov/Tracks/index.tsx
src/renderer/contexts/openGov/Tracks/types.ts
src/renderer/hooks/useOpenGovMessagePorts.ts
src/renderer/library/Hardware/HardwareStatusBar/Wrapper.ts
src/renderer/screens/OpenGov/TrackRow.tsx
src/renderer/screens/OpenGov/Tracks.tsx
src/renderer/screens/OpenGov/Wrappers.ts
src/renderer/screens/OpenGov/index.tsx
src/renderer/screens/OpenGov/types.ts

Initial implementation of the home screen on the OpenGov window.

feat: open gov window home

---

src/renderer/contexts/openGov/Referenda/defaults.ts
src/renderer/contexts/openGov/Referenda/index.tsx
src/renderer/contexts/openGov/Referenda/types.ts
src/renderer/library/Accordion/index.tsx
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/screens/OpenGov/Wrappers.ts
src/renderer/screens/OpenGov/utils.ts

Implements controls for the user to control the referenda listing in the OpenGov window.

feat: categorise + sorting open gov referenda

---

src/controller/renderer/IntervalsController.ts
src/main.ts
src/preload.ts
src/renderer/callbacks/intervaled.ts
src/renderer/contexts/main/Bootstrapping/index.tsx
src/renderer/contexts/main/IntervalSubscriptions/defaults.ts
src/renderer/contexts/main/IntervalSubscriptions/index.tsx
src/renderer/contexts/main/IntervalSubscriptions/types.ts
src/renderer/contexts/main/Manage/index.tsx
src/renderer/contexts/main/Manage/types.ts
src/renderer/contexts/openGov/ReferendaSubscriptions/defaults.ts
src/renderer/contexts/openGov/ReferendaSubscriptions/index.tsx
src/renderer/contexts/openGov/ReferendaSubscriptions/types.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/hooks/useOpenGovMessagePorts.ts
src/renderer/library/Header/index.tsx
src/renderer/screens/Home/Manage/Accounts.tsx
src/renderer/screens/Home/Manage/IntervalRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/Home/Wrappers.ts
src/types/preload.ts

Implementations for interval subscription control handlers, including:
- Removing the subscription
- Executing one-shots
- Toggling native OS notifications
- Toggling on and off the interval subscription

feat: interval subscription controls

---

src/config/subscriptions/interval.ts
src/controller/renderer/IntervalsController.ts
src/renderer/screens/Home/Manage/IntervalRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx

Enabled setting an interval duration for each added OpenGov subscription.

feat: subscription interval selector

---

src/config/chains.ts
src/controller/main/EventsController.ts
src/controller/renderer/EventsController.ts
src/controller/renderer/NotificationsController.ts
src/renderer/callbacks/intervaled.ts
src/renderer/screens/Home/Events/Item.tsx
src/renderer/screens/Home/Events/NoEvents.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/types/reporter.ts
src/utils/EventUtils.ts

Event items are implemented for each initial OpenGov subscription and piped through the application for rendering during a callback.

feat: initial open gov event items

---

src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/screens/OpenGov/Tracks/TrackRow.tsx
src/renderer/screens/OpenGov/Tracks/Wrappers.ts
src/renderer/screens/OpenGov/Tracks/index.tsx
src/renderer/utils/common.tsx

UI iteration on tabular data rendering in OpenGov window.

chore: open gov tabular data ui iteration

---

src/config/help.ts
src/config/subscriptions/interval.ts
src/renderer/Providers.tsx
src/renderer/Router.tsx
src/renderer/Wrappers.ts
src/renderer/contexts/openGov/Referenda/index.tsx
src/renderer/contexts/openGov/Referenda/types.ts
src/renderer/contexts/openGov/ReferendaSubscriptions/defaults.ts
src/renderer/contexts/openGov/ReferendaSubscriptions/index.tsx
src/renderer/contexts/openGov/ReferendaSubscriptions/types.ts
src/renderer/contexts/openGov/TaskHandler/defaults.ts
src/renderer/contexts/openGov/TaskHandler/index.tsx
src/renderer/contexts/openGov/TaskHandler/types.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/screens/Home/Events/index.tsx
src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/screens/OpenGov/types.ts
src/renderer/utils/common.tsx

feat: referenda subscriptions ui iteration

---

src/renderer/screens/Home/Manage/IntervalRow.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/utils/renderingUtils.ts

Renders the selected interval duration as a badge over the interval selector control.
Users can view the current interval duration for each active OpenGov subscription.

chore: interval duration badge

---

src/controller/main/WebsocketsController.ts
src/main.ts
src/preload.ts
src/renderer/contexts/settings/Workspaces/defaults.ts
src/renderer/contexts/settings/Workspaces/index.tsx
src/renderer/contexts/settings/Workspaces/types.ts
src/renderer/screens/Settings/Workspaces/Confirm.tsx
src/renderer/screens/Settings/Workspaces/WorkspaceRow.tsx
src/renderer/screens/Settings/Workspaces/index.tsx
src/renderer/screens/Settings/Wrappers.tsx
src/renderer/screens/Settings/types.ts
src/types/preload.ts

This PR implements a `useWorkspaces` context for the settings window to manage and manipulate workspace state.
The Websocket server `workspace` listener receives and processes one workspace data structure. The `workspaces` message (with an appended `s`) receives and processes an array of workspace data structures.

feat: workspaces sockets foundation

---

src/renderer/screens/Home/Wrappers.ts
src/renderer/screens/OpenGov/Wrappers.ts
src/renderer/screens/OpenGov/index.tsx

- Polkadot pink themed gradient background added for "no accounts" components.

chore: polish no accounts component

---

entitlements/extendedInfo.plist
src/config/help.ts
src/config/processes/main.ts
src/config/settings.ts
src/main.ts
src/renderer/contexts/common/Help/types.ts
src/renderer/contexts/main/AppSettings/defaults.ts
src/renderer/contexts/main/AppSettings/index.tsx
src/renderer/contexts/main/AppSettings/types.ts
src/renderer/contexts/settings/SettingFlags/index.tsx
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/screens/Settings/types.ts
src/utils/SystemUtils.ts
src/utils/WindowUtils.ts

Implements a `Hide Dock Icon` setting.

feat: dock icon toggle setting

---

forge.config.ts
src/renderer/Theme.tsx

- Disable theme changes when the OS theme is changed between light and dark mode.
- The Polkadot Live light theme needs further development before dynamic themes can be enabled.

fix: debugging tasks

---

src/renderer/screens/Home/Manage/PermissionRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx

Fix unresponsive `OS Notifications` checkbox edge case.

fix: os notification toggle

---

src/controller/renderer/IntervalsController.ts

The `IntervalsController` takes into account a task's `enableOsNotifications` flag to determine which OS notifications to display.

fix: interval os notifications

---

src/controller/renderer/EventsController.ts

Update the Polkadot Staking Dashboard URI for appropriate event items.

chore: update staking dashboard uri

---

src/renderer/contexts/import/AddHandler/index.tsx
src/renderer/contexts/import/ImportHandler/index.tsx
src/renderer/library/Hardware/HardwareAddress/index.tsx
src/renderer/library/Hardware/HardwareAddress/types.ts
src/renderer/screens/Import/Addresses/types.ts
src/renderer/screens/Import/Ledger/Address.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/Ledger/index.tsx
src/renderer/screens/Import/ReadOnly/Address.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Address.tsx
src/renderer/screens/Import/Vault/Manage.tsx
src/renderer/screens/Import/Vault/Reader.tsx
src/renderer/screens/Import/Vault/Splash.tsx
src/renderer/screens/Import/Vault/index.tsx
src/renderer/screens/Import/index.tsx
src/renderer/screens/Import/types.ts

chore(accounts): remove address index property

---

src/controller/main/AddressesController.ts
src/main.ts

Refactor back-end address handling logic into an `AddressesController` static class. Handles store operations for addresses.

chore(accounts): addresses controller

---

src/config/help.ts
src/config/subscriptions/account.ts
src/controller/renderer/EventsController.ts
src/controller/renderer/NotificationsController.ts
src/model/QueryMultiWrapper.ts
src/orchestrators/TaskOrchestrator.ts
src/renderer/callbacks/index.ts
src/renderer/callbacks/nominating.ts
src/renderer/callbacks/oneshots.ts
src/renderer/contexts/common/Help/types.ts
src/renderer/screens/Home/Manage/PermissionRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/types/subscriptions.ts
src/utils/AccountUtils.ts
src/utils/EventUtils.ts

Fixes and improvements to the direct nominating subscriptions.
[feat(subscriptions): nominations changed subscription](https://github.com/polkadot-live/polkadot-live-app/pull/640)
Initial implementation of the `nominating:nominations` subscription.
[chore(subscriptions): fix nominating pending payouts](https://github.com/polkadot-live/polkadot-live-app/pull/641)
Implements the new `Era Rewards` nominating subscription.

chore(subscriptions): nominating subscriptions iteration

---

src/controller/main/AddressesController.ts
src/renderer/contexts/import/ImportHandler/index.tsx
src/renderer/contexts/import/ImportHandler/types.ts
src/renderer/hooks/useImportMessagePorts.ts
src/renderer/hooks/useMainMessagePorts.ts

Backup codebase augmented to allow exporting and importing ledger accounts.

chore: export + import ledger accounts

---

src/config/help.ts

Updated help text for export + import settings.

chore: update help text

---

src/controller/main/AddressesController.ts
src/controller/main/IntervalsController.ts
src/main.ts

Moves interval subscription handling in the main process to a dedicated controller class.

chore: main process intervals controller

---

src/controller/main/EventsController.ts
src/controller/renderer/ExtrinsicsController.ts
src/main.ts
src/preload.ts
src/renderer/callbacks/index.ts
src/renderer/callbacks/intervaled.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/screens/Home/Events/Item.tsx
src/renderer/screens/Home/index.tsx
src/types/communication.ts
src/types/preload.ts

Refactor the preload API to handle event tasks with a generic IPC message.
Simplifies the preload API and unifies event task handling logic within the main process.

chore: events ipcs refactor

---

src/controller/main/OnlineStatusController.ts
src/main.ts
src/model/Api.ts
src/orchestrators/TaskOrchestrator.ts
src/preload.ts
src/renderer/contexts/main/Bootstrapping/index.tsx
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/library/Menu/index.tsx
src/types/communication.ts
src/types/preload.ts

Refactor the preload API to handle connection tasks with a generic IPC message.
Simplifies the preload API and unifies connection task handling logic within the main process.

chore: connection ipcs refactor

---

src/renderer/Providers.tsx
src/renderer/contexts/tabs/Tabs/defaults.ts
src/renderer/contexts/tabs/Tabs/index.tsx
src/renderer/contexts/tabs/Tabs/types.ts
src/renderer/screens/Tabs/index.tsx

Implementation of an initial tabs context, lifting tab logic out of the React tab components.

chore: initial tabs context

---

src/controller/main/BackupController.ts
src/controller/main/EventsController.ts
src/controller/main/WebsocketsController.ts
src/controller/main/WindowsController.ts
src/ledger/index.ts
src/main.ts
src/orchestrators/AppOrchestrator.ts
src/preload.ts
src/renderer/Wrappers.ts
src/renderer/screens/Import/Home.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/Ledger/Splash.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Manage.tsx
src/renderer/screens/Import/Vault/Splash.tsx
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/screens/OpenGov/Tracks/index.tsx
src/renderer/screens/OpenGov/index.tsx
src/renderer/screens/Settings/index.tsx
src/renderer/screens/Tabs/index.tsx
src/renderer/utils/common.tsx
src/types/preload.ts
src/utils/SystemUtils.ts
src/utils/WdioUtils.ts
src/utils/WindowUtils.ts

Infrastructure to open child windows as views in the tabbed base window.
**In progress...**

chore: child window views

---

src/controller/main/WindowsController.ts
src/main.ts
src/preload.ts
src/renderer/contexts/tabs/Tabs/defaults.ts
src/renderer/contexts/tabs/Tabs/index.tsx
src/renderer/contexts/tabs/Tabs/types.ts
src/renderer/screens/Tabs/index.tsx
src/types/communication.ts
src/types/preload.ts
src/utils/WindowUtils.ts

chore: base window dynamic tabs

---

src/controller/main/WindowsController.ts
src/main.ts
src/preload.ts
src/renderer/contexts/tabs/Tabs/index.tsx
src/renderer/hooks/useDebug.ts
src/renderer/screens/Action/index.tsx
src/renderer/screens/Import/index.tsx
src/renderer/screens/OpenGov/index.tsx
src/renderer/screens/Settings/index.tsx
src/renderer/screens/Tabs/index.tsx
src/types/preload.ts
src/utils/WindowUtils.ts

- Explicit background colour set for created  base window views.
- `useDebug` hook opens a view's dev tools via the `Shift+D` hotkey (only works in `DEBUG` mode).
- Styling and markup improvements.

chore: views debugging + devTools hotkey

---

src/controller/main/WindowsController.ts
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/screens/OpenGov/Tracks/index.tsx
src/renderer/screens/Tabs/index.tsx
src/renderer/utils/common.tsx

- Un-hide base window when opening a view.
- Fix placeholder rendering CSS.
- Render side borders in tab view.

fix: base window debugging

---

src/renderer/screens/Tabs/index.tsx
src/utils/WindowUtils.ts

Styling iteration for the tabs view in the base window.

chore: tabs styling

---

src/controller/main/AddressesController.ts
src/controller/main/BackupController.ts
src/controller/main/EventsController.ts
src/renderer/contexts/import/ImportHandler/index.tsx
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/utils/ImportUtils.ts

Augments the backup system by exporting persisted events data to a text file.

feat: export events data

---

src/controller/main/AddressesController.ts
src/controller/main/EventsController.ts
src/controller/renderer/EventsController.ts
src/renderer/contexts/main/Events/defaults.ts
src/renderer/contexts/main/Events/index.tsx
src/renderer/contexts/main/Events/types.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/utils/ImportUtils.ts
src/types/communication.ts

Augments the backup system by implementing the importing of events data from an exported text file.

feat: import events data

---

src/controller/main/AddressesController.ts
src/controller/main/BackupController.ts
src/controller/main/IntervalsController.ts
src/renderer/contexts/main/Bootstrapping/index.tsx

Augments the backup system by exporting persisted interval subscription task data to a text file.

feat: export interval subscriptions

---

src/controller/main/IntervalsController.ts
src/controller/renderer/IntervalsController.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/screens/Home/Manage/IntervalRow.tsx
src/renderer/utils/ImportUtils.ts
src/types/communication.ts

Augments the backup system by implementing the importing of interval subscription tasks from an exported text file.

feat: import interval subscriptions

---

src/controller/main/BackupController.ts
src/controller/main/SubscriptionsController.ts
src/renderer/hooks/useImportMessagePorts.ts
src/types/accounts.ts

Augments the backup system by exporting all imported accounts subscription task data to a text file.

feat: export account subscriptions

---

src/controller/main/SubscriptionsController.ts
src/controller/renderer/AccountsController.ts
src/controller/renderer/SubscriptionsController.ts
src/renderer/contexts/main/Bootstrapping/index.tsx
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/utils/ImportUtils.ts
src/types/communication.ts

Augments the backup system by implementing the importing of account subscriptions from an exported text file.

feat: import account subscriptions

---

src/renderer/Providers.tsx
src/renderer/contexts/main/DataBackup/default.ts
src/renderer/contexts/main/DataBackup/index.tsx
src/renderer/contexts/main/DataBackup/types.ts
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/utils/ImportUtils.ts

Lift data backup logic into a context in the main renderer.

chore: data backup context

---

src/controller/main/BackupController.ts
src/controller/main/EventsController.ts
src/controller/main/WindowsController.ts
src/controller/renderer/AccountsController.ts
src/renderer/contexts/import/AddHandler/index.tsx
src/renderer/contexts/import/ImportHandler/index.tsx
src/renderer/contexts/import/RemoveHandler/index.tsx
src/renderer/contexts/import/RemoveHandler/types.ts
src/renderer/contexts/main/DataBackup/index.tsx
src/renderer/hooks/useMainMessagePorts.ts
src/renderer/screens/Home/Manage/index.tsx
src/renderer/screens/Import/Addresses/Remove.tsx
src/renderer/screens/Import/Addresses/types.ts
src/renderer/screens/Import/Ledger/Address.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/Ledger/index.tsx
src/renderer/screens/Import/ReadOnly/Address.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Address.tsx
src/renderer/screens/Import/Vault/Manage.tsx
src/renderer/screens/Import/Vault/index.tsx
src/renderer/screens/Import/types.ts

Bug fixes and logic improvements in the augmented backup system.

fix: data backup debugging

---

src/config/help.ts
src/controller/renderer/AccountsController.ts
src/renderer/contexts/common/Help/types.ts
src/renderer/contexts/main/Addresses/defaults.ts
src/renderer/contexts/main/Addresses/index.tsx
src/renderer/contexts/main/Addresses/types.ts
src/renderer/contexts/main/Events/defaults.ts
src/renderer/contexts/main/Events/index.tsx
src/renderer/contexts/main/Events/types.ts
src/renderer/contexts/main/IntervalSubscriptions/defaults.ts
src/renderer/contexts/main/IntervalSubscriptions/index.tsx
src/renderer/contexts/main/IntervalSubscriptions/types.ts
src/renderer/library/Header/index.tsx
src/renderer/screens/Home/Manage/Summary.tsx
src/renderer/screens/Home/index.tsx

Initial foundations of the summary page.

feat: initial summary page

---

src/renderer/kits/Buttons/index.scss
src/renderer/library/ShiftingMeter/ShiftingMeter.styles.ts
src/renderer/library/ShiftingMeter/ShiftingMeter.tsx
src/renderer/library/ShiftingMeter/index.ts
src/renderer/screens/Home/Manage/Summary.tsx

Implements a "odometer" like library component to animate shifting numbers.
Summary page uses the `ShiftingMeter` component to animate numbers when stats change.

feat: number meter component

---

src/renderer/library/Stats/Stats.styles.ts
src/renderer/library/Stats/StatsSection.tsx
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/Home/Events/index.tsx
src/renderer/screens/Home/Manage/Accounts.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/Home/Manage/index.tsx
src/renderer/screens/Home/Wrappers.ts

Add titles to main window screens - consistent with the summary screen.

feat: main window screen titles

---

src/renderer/screens/Tabs/Tab.tsx
src/renderer/screens/Tabs/Wrappers.tsx
src/renderer/screens/Tabs/index.tsx
src/renderer/screens/Tabs/types.ts

The base window tabs styling is consistent with the main window's side nav.

chore: base window tabs iteration

---

src/renderer/library/components/Accordion/Accordion.tsx
src/renderer/library/components/Accordion/AccordionHeaders.styles.ts
src/renderer/library/components/Accordion/AccordionHeaders.tsx
src/renderer/library/components/Accordion/types.ts
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/Home/Events/index.tsx
src/renderer/screens/Home/Manage/Accounts.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/Home/Manage/index.tsx
src/renderer/screens/Import/Ledger/Manage.tsx
src/renderer/screens/Import/ReadOnly/Manage.tsx
src/renderer/screens/Import/Vault/Manage.tsx
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/screens/OpenGov/Referenda/index.tsx
src/renderer/screens/Settings/Wrappers.tsx
src/renderer/screens/Settings/index.tsx

Styling the accordion components.

feat: accordion styling iteration

---

src/renderer/library/components/Accordion/AccordionHeaders.styles.ts
src/renderer/library/components/Common/Help.ts
src/renderer/library/components/Common/index.ts
src/renderer/library/components/Stats/Stats.styles.ts
src/renderer/screens/Home/Events/Wrappers.tsx
src/renderer/screens/Home/Events/index.tsx
src/renderer/screens/Home/Manage/Accounts.tsx
src/renderer/screens/Home/Manage/IntervalRow.tsx
src/renderer/screens/Home/Manage/PermissionRow.tsx
src/renderer/screens/Home/Manage/Permissions.tsx
src/renderer/screens/Home/Manage/Wrappers.tsx
src/renderer/screens/Home/Manage/index.tsx

Styling the subscription screen components.

feat: subscription screen styling

---

src/renderer/screens/Settings/Wrappers.tsx
src/renderer/screens/Settings/index.tsx

Styling of the settings screen.

feat: settings screen styling

---

src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/screens/OpenGov/Referenda/index.tsx

Standardising the referenda screen styling in the Open Gov window.

feat: open gov referenda styling

---

src/model/Track.ts
src/renderer/library/styles/StatsFooter.ts
src/renderer/screens/OpenGov/Tracks/TrackRow.tsx
src/renderer/screens/OpenGov/Tracks/Wrappers.ts
src/renderer/screens/OpenGov/Tracks/index.tsx

Styling the Open Gov window Tracks screen.

feat: open gov tracks styling

---

src/renderer/library/components/Hardware/HardwareAddress/HardwareAddress.tsx
src/renderer/library/components/Hardware/HardwareAddress/Wrapper.ts
src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/theme/theme.scss

Tweaks to the styling iteration.

chore: styling tweaks

---

src/renderer/screens/OpenGov/Referenda/Wrappers.ts
src/renderer/theme/theme.scss

Small tweaks to referenda row buttons.

chore: theme tweaks

---

src/renderer/screens/Home/Wrappers.ts

Fixes theming on the no accounts wrapper component.

fix: no accounts wrapper theming

---

package.json
packages/renderer/src/renderer/Providers.tsx
packages/renderer/src/renderer/contexts/main/CogMenu/defaults.ts
packages/renderer/src/renderer/contexts/main/CogMenu/index.tsx
packages/renderer/src/renderer/contexts/main/CogMenu/types.ts
packages/renderer/src/renderer/screens/Home/index.tsx
packages/ui/gulpfile.js
packages/ui/src/components/Menu/index.tsx

Lift code that controls the cog menu into a context.

chore: cog menu context

---

packages/main/src/controller/WindowsController.ts
packages/main/src/main.ts
packages/main/src/utils/WindowUtils.ts
packages/preload/src/preload.ts
packages/preload/tests/unit.spec.ts
packages/renderer/src/config/settings.ts
packages/renderer/src/model/Api.ts
packages/renderer/src/renderer/screens/Home/index.tsx
packages/types/src/preload.ts
packages/ui/src/components/Header/Wrapper.ts
packages/ui/src/components/Header/index.tsx
packages/ui/src/components/Header/types.ts
packages/ui/tests/Header.spec.tsx
packages/ui/tests/NavCard.spec.tsx
packages/ui/tests/NavCardThin.spec.tsx
packages/ui/tests/SideNav.spec.tsx

Adds a minimise window button in the main window header for Linux platforms.
The main window will minimise to the desktop environment's taskbar or dock.

feat: linux minimise window button

---

.github/workflows/release-linux.yml

GitHub actions workflow for publishing a Linux AppImage.

chore: linux release workflow

---

package.json
packages/main/src/ledger/index.ts
packages/main/src/main.ts
packages/preload/src/preload.ts
packages/renderer/src/config/svg/polkadotIcon.svg
packages/renderer/src/renderer/screens/Import/Ledger/Import/Wrappers.ts
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Manage.tsx
packages/renderer/src/renderer/screens/Import/Ledger/index.tsx
packages/types/src/ledger.ts
packages/types/src/preload.ts
yarn.lock

Hooking up the new UI for importing ledger addresses into Polkadot Live.
Enables users to seamlessly fetch and select Polkadot + Kusama addresses derived from a connected Ledger device.

feat: fetching multiple ledger addresses

---

packages/renderer/src/renderer/screens/Import/Ledger/Import/InfoCardSteps.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Import/Wrappers.ts
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/theme/theme.scss

Implements a new `InfoCardSteps` component and polishing the Ledger import UI.

feat: ledger ui polish

---

packages/renderer/src/renderer/Providers.tsx
packages/renderer/src/renderer/contexts/import/WalletConnect/defaults.ts
packages/renderer/src/renderer/contexts/import/WalletConnect/index.tsx
packages/renderer/src/renderer/contexts/import/WalletConnect/types.ts
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/types.ts

Implements an initial WalletConnect context and lifts WalletConnect logic from component to context.

feat: wallet connect context

---

package.json
packages/renderer/src/renderer/Providers.tsx
packages/renderer/src/renderer/contexts/import/LedgerHardware/index.tsx
packages/renderer/src/renderer/contexts/import/WalletConnect/defaults.ts
packages/renderer/src/renderer/contexts/import/WalletConnect/index.tsx
packages/renderer/src/renderer/contexts/import/WalletConnect/types.ts
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
yarn.lock

WalletConnect import UI implementation:
- Detects and restores a WalletConnect session if one exists.
- Allows disconnecting from a restored WalletConnect session.
- Allows connecting to a new WalletConnect session.
- Responds to online and offline modes.

feat: wallet connect dynamic ui

---

packages/renderer/src/renderer/contexts/import/WalletConnect/defaults.ts
packages/renderer/src/renderer/contexts/import/WalletConnect/index.tsx
packages/renderer/src/renderer/contexts/import/WalletConnect/types.ts
packages/renderer/src/renderer/screens/Import/index.tsx

chore: wallet connect optimisation

---

packages/renderer/src/renderer/theme/theme.scss
packages/renderer/src/renderer/theme/variables.ts
packages/ui/src/components/Help/Wrappers.ts
packages/ui/src/kits/Overlay/index.scss

Improves the theming and styling of help overlay definitions.

chore: help overlay definitions styling

---

.github/dependabot.yml

Remove redundant dependabot groups.

chore: dependabot cleanup

---

packages/renderer/src/renderer/screens/Action/Signer.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Action/types.ts
packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/ui/src/components/Tx/Wrapper.ts
packages/ui/src/components/Tx/index.tsx

Some cleanup and refactors to the Action window's Tx components, in preparation for upcoming changes.

chore: tx component cleanup

---

packages/main/src/controller/EventsController.ts
packages/renderer/src/controller/EventsController.ts
packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/types/package.json
packages/types/src/index.ts
packages/types/src/legacy.ts
packages/types/src/reporter.ts

Use separate types for URI actions and Tx actions on events.
Introduces legacy types for backward compatibility. Will be used when importing data from previous versions.

chore: event action type refactors

---

package.json
packages/renderer/src/renderer/screens/Action/Accordion/Wrappers.ts
packages/renderer/src/renderer/screens/Action/Accordion/index.tsx
packages/renderer/src/renderer/screens/Action/TxActionItem.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/ui/src/components/Tx/Wrapper.ts
yarn.lock

Accordion component using Radix UI to organise extrinsic entries in the actions window.

feat: extrinsics accordion

---

package.json
packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
packages/renderer/src/renderer/screens/Action/Accordion/Wrappers.ts
packages/renderer/src/renderer/screens/Action/Accordion/index.tsx
packages/renderer/src/renderer/screens/Action/DropdownMenu/Wrappers.ts
packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/DropdownMenu/types.ts
packages/renderer/src/renderer/screens/Action/index.tsx
yarn.lock

Dropdown menu component for executing individual extrinsic item actions.

feat: extrinsic item dropdown menu

---

packages/renderer/src/renderer/contexts/main/CogMenu/index.tsx
packages/renderer/src/renderer/screens/Action/Accordion/Wrappers.ts
packages/renderer/src/renderer/screens/Action/Accordion/index.tsx
packages/renderer/src/renderer/screens/Action/TxActionItem.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/ui/src/components/Tx/Wrapper.ts

Extrinsics cog menu item and UI tweaks.

feat: extrinsics cog menu item

---

packages/main/src/utils/WindowUtils.ts
packages/preload/src/preload.ts
packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/renderer/src/renderer/screens/Home/index.tsx
packages/types/src/communication.ts
packages/types/src/preload.ts

Port tasks are relayed to the target window after its opened.
If the target window is already open, the port task is sent directly.

feat: extrinsics window messaging

---

packages/main/src/utils/WindowUtils.ts
packages/preload/src/preload.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/renderer/src/renderer/screens/Home/index.tsx
packages/types/src/communication.ts
packages/types/src/preload.ts

Behavior tweak when adding extrinsics and changing the selected account filter.

fix: extrinsics selected account filter

---

packages/renderer/src/config/chains.ts
packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/DropdownMenu/types.ts
packages/renderer/src/renderer/screens/Action/Signer.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/ui/src/components/Tx/index.tsx

chore: extrinsic item ui iteration

---

packages/main/src/config/main.ts
packages/main/src/main.ts
packages/renderer/src/config/chains.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/common/Connections/defaults.ts
packages/renderer/src/renderer/contexts/common/Connections/index.tsx
packages/renderer/src/renderer/contexts/common/Connections/types.ts
packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Home/Events/Item.tsx

Disables building multiple extrinsics at the same time. 
Makes sure only one extrinsic is processing at a time, preventing state/messaging bugs.

chore: synchronous extrinsic processing

---

packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
packages/renderer/src/renderer/hooks/useActionMessagePorts.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/screens/Action/Signer.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/types/src/tx.ts

Extrinsics are built whenever the corresponding `Sign` button is clicked.
The signing account's current nonce is fetched, keeping the extrinsic valid.

chore: extrinsics flow iteration

---

packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
packages/renderer/src/renderer/hooks/useActionMessagePorts.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/DropdownMenu/types.ts
packages/renderer/src/renderer/screens/Action/Signer.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Action/types.ts

UX improvements when submitting extrinsics.

chore: extrinsics submission flow iteration

---

packages/main/src/controller/WindowsController.ts
packages/main/src/main.ts
packages/preload/src/preload.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/common/Connections/index.tsx
packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/Signer.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/types/src/communication.ts
packages/types/src/preload.ts

Some cleanup on the extrinsics code. Extrinsic signing disabled in offline mode.

chore: extrinsics code cleanup

---

packages/main/src/controller/ExtrinsicsController.ts
packages/main/src/main.ts
packages/preload/src/preload.ts
packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/renderer/contexts/action/TxMeta/defaults.ts
packages/renderer/src/renderer/contexts/action/TxMeta/index.tsx
packages/renderer/src/renderer/contexts/action/TxMeta/types.ts
packages/renderer/src/renderer/hooks/useActionMessagePorts.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/types/src/communication.ts
packages/types/src/preload.ts
packages/types/src/tx.ts

Initial implementation of persisting and removing extrinsics from the store.

feat: persist + remove extrinsics from store

---

packages/renderer/src/config/chains.ts
packages/renderer/src/renderer/contexts/import/LedgerHardware/defaults.ts
packages/renderer/src/renderer/contexts/import/LedgerHardware/index.tsx
packages/renderer/src/renderer/contexts/import/LedgerHardware/types.ts
packages/renderer/src/renderer/screens/Import/Ledger/Import/Wrappers.ts
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/types/src/chains/index.ts

Lift select network config from context to config file.

chore: lift select network config

---

package.json
packages/main/src/main.ts
packages/preload/src/preload.ts
packages/renderer/src/renderer/screens/Home/Send/Wrappers.ts
packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/renderer/screens/Home/Send/types.ts
packages/types/src/preload.ts
yarn.lock

Augments the send screen UX. 
Implements a button that enables the user to copy selected sender and receiver addresses to the clipboard.

feat: copy address to clipboard

---

packages/renderer/src/renderer/screens/Action/ExtrinsicItemContent.tsx
packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
packages/renderer/src/renderer/screens/Import/Wrappers.ts
packages/renderer/src/renderer/theme/theme.scss
packages/ui/src/components/Cards/InfoCard.styles.ts
packages/ui/src/components/Cards/InfoCard.tsx
packages/ui/src/components/Cards/index.ts

Moves info card component to UI library. Adds info to transfer extrinsic items and the send screen.

chore: refactor card ui components

---

packages/renderer/src/renderer/screens/Action/Helpers.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/ui/src/components/AccordionRx/Wrappers.ts
packages/ui/src/components/ActionItem/index.tsx
packages/ui/src/components/ActionItem/types.ts

Improve extrinsic item headers in the extrinsics window.

chore: improved extrinsic item headers

---

.github/dependabot.yml

Limit open pull requests to 10.

chore: dependabot config tweak

---

packages/renderer/src/renderer/screens/Action/ExtrinsicItemContent.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Action/types.ts
packages/ui/src/components/AccordionRx/Wrappers.ts
packages/ui/src/components/Tx/Wrapper.ts
packages/ui/src/styles/flex.ts

Simplify extrinsic item trigger UI and clean up extrinsic item content inline styles.

chore: extrinsic item ui polish

---

packages/renderer/src/renderer/screens/Home/Manage/Permissions.tsx
packages/renderer/src/renderer/screens/Home/Manage/Wrappers.tsx
packages/renderer/src/renderer/screens/Home/Send/SendHelpers.tsx
packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/renderer/screens/Home/Summary/Wrappers.tsx
packages/renderer/src/renderer/screens/Home/Summary/index.tsx
packages/renderer/src/renderer/screens/Home/Summary/types.ts
packages/ui/src/components/AccordionRx/AccordionRx.tsx
packages/ui/src/components/AccordionRx/Wrappers.ts
packages/ui/src/components/Stats/Stats.styles.ts
packages/ui/src/components/Stats/StatsSection.tsx
packages/ui/src/styles/flex.ts

Polish summary screen iteration:
- Integrate radix-ui accordion components
- Render subscription stats as columns with account name and identicon
- Abstracts reusable components
- More consistent styling

chore: summary screen polish

---

packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/renderer/screens/Settings/index.tsx
packages/ui/src/components/AccordionRx/Wrappers.ts

Use radix-ui accordion components on settings screen.

chore: settings screen polish

---

packages/renderer/src/renderer/screens/Action/Helpers.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/renderer/screens/Home/Summary/index.tsx
packages/renderer/src/renderer/screens/Import/Home.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Import/Wrappers.ts
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Manage.tsx
packages/renderer/src/renderer/screens/Import/ReadOnly/Manage.tsx
packages/renderer/src/renderer/screens/Import/Vault/Manage.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/Wrappers.ts
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Manage.tsx
packages/renderer/src/renderer/screens/Import/Wrappers.ts
packages/renderer/src/renderer/screens/Settings/index.tsx
packages/renderer/src/utils/AccountUtils.ts
packages/ui/src/components/AccordionRx/Wrappers.ts

chore: accounts screen polish

---

packages/renderer/src/renderer/contexts/openGov/TaskHandler/index.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Manage.tsx
packages/renderer/src/renderer/screens/Import/ReadOnly/Manage.tsx
packages/renderer/src/renderer/screens/Import/Vault/Manage.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Manage.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Tracks/index.tsx
packages/renderer/src/renderer/screens/OpenGov/index.tsx
packages/renderer/src/renderer/screens/Wrappers.ts
packages/ui/src/components/ActionItem/Wrapper.ts

Action item additions and radix-ui accordion components used in the OpenGov window.

chore: open gov screen polish

---

packages/renderer/src/renderer/screens/Home/Events/Category.tsx
packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/renderer/src/renderer/screens/Home/Events/index.tsx
packages/renderer/src/renderer/screens/Home/Events/types.ts
packages/ui/src/components/TooltipRx/TooltipRx.tsx
packages/ui/src/components/TooltipRx/types.ts

Use radix-ui components for events screen.

chore: events screen polish

---

packages/renderer/src/renderer/contexts/main/Manage/defaults.ts
packages/renderer/src/renderer/contexts/main/Manage/index.tsx
packages/renderer/src/renderer/contexts/main/Manage/types.ts
packages/renderer/src/renderer/screens/Home/Events/Category.tsx
packages/renderer/src/renderer/screens/Home/Events/index.tsx
packages/renderer/src/renderer/screens/Home/Manage/Accounts.tsx
packages/renderer/src/renderer/screens/Home/Manage/IntervalRow.tsx
packages/renderer/src/renderer/screens/Home/Manage/PermissionRow.tsx
packages/renderer/src/renderer/screens/Home/Manage/Permissions.tsx
packages/renderer/src/renderer/screens/Home/Manage/Wrappers.tsx
packages/renderer/src/renderer/screens/Home/Summary/Wrappers.tsx
packages/renderer/src/renderer/screens/Home/Summary/index.tsx
packages/renderer/src/renderer/utils/renderingUtils.ts

- Radix components integration for the subscription screens
- Accordion behaviour improvements
- Component refactoring cleanup

chore: subscriptions screen polish

---

packages/renderer/src/renderer/screens/Action/index.tsx

List account names alphabetically in the extrinsics window's account filter select box.

chore: extrinsics filter account select box order

---

packages/renderer/src/renderer/screens/Settings/Setting.tsx
packages/renderer/src/renderer/screens/Settings/Wrappers.tsx
packages/renderer/src/renderer/screens/Settings/index.tsx

Augmenting the settings view styling to make the UI fully responsive.

feat: responsive settings view

---

packages/renderer/src/renderer/screens/Tabs/Wrappers.tsx
packages/renderer/src/renderer/theme/theme.scss
packages/renderer/src/renderer/theme/variables.ts
packages/ui/src/styles/ScrollWrappers.ts

Augmenting the tabs view styling to make the UI fully responsive.

feat: responsive tabs view

---

packages/main/src/utils/WindowUtils.ts
packages/renderer/src/renderer/Utils.tsx
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Import/Home.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/renderer/screens/Import/Ledger/Manage.tsx
packages/renderer/src/renderer/screens/Import/ReadOnly/Manage.tsx
packages/renderer/src/renderer/screens/Import/Vault/Manage.tsx
packages/renderer/src/renderer/screens/Import/Vault/Splash.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Import/index.tsx
packages/renderer/src/renderer/screens/Import/WalletConnect/Manage.tsx
packages/renderer/src/renderer/screens/Import/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/Referenda/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Tracks/TrackRow.tsx
packages/renderer/src/renderer/screens/OpenGov/Tracks/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/Tracks/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/index.tsx
packages/renderer/src/renderer/screens/OpenGov/types.ts
packages/renderer/src/renderer/screens/Settings/Wrappers.tsx
packages/renderer/src/renderer/screens/Settings/index.tsx
packages/renderer/src/renderer/screens/Wrappers.ts
packages/ui/src/components/ActionItem/Wrapper.ts
packages/ui/src/components/Footers/LinksFooter.tsx
packages/ui/src/components/Footers/index.ts
packages/ui/src/components/Wrappers/index.tsx
packages/ui/src/components/index.ts
packages/ui/src/styles/ScrollWrappers.ts
packages/ui/src/styles/flex.ts

- Renders a "links" footer at the bottom of child views.
- Large cleanups to view markup and flex structure.

feat: view footer

---

package.json
packages/main/src/controller/WindowsController.ts
packages/main/src/main.ts
packages/main/src/utils/WindowUtils.ts
packages/preload/src/preload.ts
packages/renderer/src/renderer/screens/Tabs/ResizeToggles.styles.ts
packages/renderer/src/renderer/screens/Tabs/ResizeToggles.tsx
packages/renderer/src/renderer/screens/Tabs/WindowToggles.tsx
packages/renderer/src/renderer/screens/Tabs/Wrappers.tsx
packages/renderer/src/renderer/screens/Tabs/index.tsx
packages/types/src/preload.ts
yarn.lock

Adds a toggle group to the tabs view to resize the base window based on three size presets.

feat: base window resize toggles

---

packages/renderer/src/renderer/screens/OpenGov/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/index.tsx
packages/ui/src/components/Cards/NavCard.tsx
packages/ui/src/components/Cards/types.ts

Improve the OpenGov home grid design.

chore: open gov home grid iteration

---

packages/renderer/src/renderer/screens/OpenGov/Overview/OverviewExplore.tsx
packages/renderer/src/renderer/screens/OpenGov/Overview/OverviewTreasury.tsx
packages/renderer/src/renderer/screens/OpenGov/Overview/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Overview/types.ts
packages/renderer/src/renderer/screens/OpenGov/index.tsx

Break up OpenGov overview screen into manageable de-coupled components.

chore: open gov component refactoring

---

packages/renderer/src/renderer/contexts/openGov/Polkassembly/index.tsx
packages/renderer/src/renderer/contexts/openGov/Polkassembly/types.ts
packages/renderer/src/renderer/screens/Action/DropdownMenu/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/types.ts
packages/renderer/src/renderer/screens/OpenGov/Referenda/InfoOverlay.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/Wrappers.ts
packages/renderer/src/renderer/theme/theme.scss
packages/renderer/src/renderer/theme/variables.ts
packages/types/src/openGov.ts

Improves referenda row UI by adding a dropdown menu and polishing the button components.

chore: referendum row drop down menu

---

packages/renderer/src/renderer/contexts/openGov/Referenda/defaults.ts
packages/renderer/src/renderer/contexts/openGov/Referenda/index.tsx
packages/renderer/src/renderer/contexts/openGov/Referenda/types.ts
packages/renderer/src/renderer/contexts/openGov/Tracks/defaults.ts
packages/renderer/src/renderer/contexts/openGov/Tracks/index.tsx
packages/renderer/src/renderer/contexts/openGov/Tracks/types.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/hooks/useOpenGovMessagePorts.ts
packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Overview/OverviewExplore.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/ReferendumRow.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/Wrappers.ts
packages/renderer/src/renderer/screens/OpenGov/Referenda/index.tsx

UI implemented to filter referenda by track along with other UX improvements.

feat: filter referenda by track

---

packages/renderer/src/renderer/screens/Action/Dialogs/DialogExtrinsicSummary.tsx
packages/renderer/src/renderer/screens/Action/Dialogs/Wrappers.ts
packages/renderer/src/renderer/screens/Action/Dialogs/index.ts
packages/renderer/src/renderer/screens/Action/Dialogs/types.ts
packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/DropdownMenu/types.ts
packages/renderer/src/renderer/screens/Action/ExtrinsicItemContent.tsx
packages/renderer/src/renderer/screens/Action/Helpers.tsx
packages/renderer/src/renderer/screens/Action/Wrappers.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/Action/types.ts
packages/renderer/src/renderer/screens/OpenGov/Referenda/Dialogs/DialogFindReferendum.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/Dialogs/Wrappers.ts
packages/renderer/src/renderer/theme/theme.scss
packages/renderer/src/renderer/theme/variables.ts

Implements a dialog that renders transaction summaries in the extrinsics window.

feat: extrinsic summary dialog

---

packages/renderer/src/renderer/screens/Action/DropdownMenu/index.tsx
packages/renderer/src/renderer/screens/Action/index.tsx

Control extrinsic item dropdown with state.

fix: extrinsic item dropdown state

---

packages/main/src/controller/ExtrinsicsController.ts
packages/renderer/src/config/help.ts
packages/renderer/src/renderer/contexts/main/Addresses/defaults.ts
packages/renderer/src/renderer/contexts/main/Addresses/index.tsx
packages/renderer/src/renderer/contexts/main/Addresses/types.ts
packages/renderer/src/renderer/screens/Home/Summary/OpenViewButton.tsx
packages/renderer/src/renderer/screens/Home/Summary/StatItemRow.tsx
packages/renderer/src/renderer/screens/Home/Summary/Wrappers.tsx
packages/renderer/src/renderer/screens/Home/Summary/index.tsx
packages/renderer/src/renderer/screens/Home/Summary/types.ts
packages/types/src/communication.ts
packages/types/src/help.ts
packages/ui/src/components/Stats/Stats.styles.ts

chore: summary screen iteration

---

packages/renderer/src/renderer/screens/Home/Events/Item.tsx
packages/renderer/src/renderer/screens/Home/Manage/Accounts.tsx
packages/renderer/src/renderer/screens/Home/Manage/IntervalRow.tsx
packages/renderer/src/renderer/screens/Home/Manage/PermissionRow.tsx
packages/renderer/src/renderer/screens/Home/Manage/Wrappers.tsx

UI tweaks to main window subscription screens.

chore: subscriptions screen tweaks

---

packages/renderer/src/renderer/screens/Home/Send/Dialogs/DialogRecipient.tsx
packages/renderer/src/renderer/screens/Home/Send/Dialogs/Wrappers.ts
packages/renderer/src/renderer/screens/Home/Send/Dialogs/index.ts
packages/renderer/src/renderer/screens/Home/Send/Dialogs/types.ts
packages/renderer/src/renderer/screens/Home/Send/SendHelpers.tsx
packages/renderer/src/renderer/screens/Home/Send/Wrappers.ts
packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/renderer/screens/Home/Send/types.ts

Type in an arbitrary recipient address to send native tokens, or select a managed address from the list.

feat: send screen recipient dialog

---

packages/renderer/src/renderer/hooks/useSendNative.ts
packages/renderer/src/renderer/screens/Home/Send/index.tsx

Move send screen state and logic into a hook for better code organisation.

chore: send native hook

---

packages/renderer/src/renderer/screens/Action/Dialogs/DialogExtrinsicSummary.tsx
packages/renderer/src/renderer/screens/Home/Send/Dialogs/DialogRecipient.tsx
packages/renderer/src/renderer/screens/OpenGov/Referenda/Dialogs/DialogFindReferendum.tsx
packages/ui/src/styles/dialog.ts
packages/ui/src/styles/index.ts

Moves re-usable dialog wrappers to `ui` package.

chore: dialog component migration

---

packages/renderer/src/config/processes/openGov.ts
packages/renderer/src/renderer/screens/OpenGov/index.tsx

Check if port exists before using it.

fix: open gov port

---

packages/renderer/src/controller/APIsController.ts
packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/model/Api.ts
packages/renderer/src/model/QueryMultiWrapper.ts
packages/renderer/src/orchestrators/TaskOrchestrator.ts
packages/renderer/src/renderer/callbacks/index.ts
packages/renderer/src/renderer/callbacks/intervaled.ts
packages/renderer/src/renderer/callbacks/oneshots.ts
packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/renderer/contexts/main/Chains/defaults.ts
packages/renderer/src/renderer/contexts/main/Chains/index.tsx
packages/renderer/src/renderer/contexts/main/Chains/types.ts
packages/renderer/src/renderer/contexts/main/Subscriptions/index.tsx
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/screens/Home/Footer/index.tsx
packages/renderer/src/utils/AccountUtils.ts
packages/renderer/src/utils/ApiUtils.ts
packages/renderer/src/utils/CommonUtils.ts

Footer UI dynamically updates when API instances are connected and disconnected in real time.

fix: api connections state

---

packages/main/src/main.ts
packages/renderer/src/controller/AccountsController.ts
packages/renderer/src/controller/SubscriptionsController.ts
packages/renderer/src/orchestrators/TaskOrchestrator.ts
packages/renderer/src/renderer/contexts/main/Addresses/defaults.ts
packages/renderer/src/renderer/contexts/main/Addresses/index.tsx
packages/renderer/src/renderer/contexts/main/Addresses/types.ts
packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/renderer/contexts/main/Chains/index.tsx
packages/renderer/src/renderer/contexts/main/CogMenu/index.tsx
packages/renderer/src/renderer/contexts/main/DataBackup/index.tsx
packages/renderer/src/renderer/contexts/main/Subscriptions/defaults.ts
packages/renderer/src/renderer/contexts/main/Subscriptions/index.tsx
packages/renderer/src/renderer/contexts/main/Subscriptions/types.ts
packages/renderer/src/renderer/hooks/useInitIpcHandlers.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts

Optimise updating state in static classes for subscriptions and accounts.

fix: bootstrapping state

---

packages/renderer/src/renderer/screens/OpenGov/Referenda/index.tsx

fix: referenda pagination ellipsis

---

packages/renderer/src/renderer/screens/Home/Footer/Wrapper.ts
packages/renderer/src/renderer/screens/Home/Footer/index.tsx

Adds tooltips to API disconnect buttons.

feat: api disconnect button tooltips

---

packages/renderer/src/controller/APIsController.ts
packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/model/QueryMultiWrapper.ts
packages/renderer/src/orchestrators/TaskOrchestrator.ts
packages/renderer/src/renderer/callbacks/index.ts
packages/renderer/src/renderer/callbacks/oneshots.ts
packages/renderer/src/renderer/contexts/main/Addresses/index.tsx
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/hooks/useOpenGovMessagePorts.ts
packages/renderer/src/renderer/screens/Action/Dropdowns/ExtrinsicDropdownMenu.tsx
packages/renderer/src/renderer/screens/Home/Manage/Permissions.tsx
packages/renderer/src/renderer/screens/OpenGov/Tracks/index.tsx
packages/renderer/src/utils/AccountUtils.ts
packages/renderer/src/utils/CommonUtils.ts

Handle exceptions gracefully when fetching an API instance times out and code cleanups.

feat: api timeouts and cleanup

---

packages/renderer/src/renderer/contexts/openGov/Referenda/index.tsx
packages/renderer/src/renderer/hooks/useImportMessagePorts.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/hooks/useOpenGovMessagePorts.ts
packages/renderer/src/renderer/screens/Action/index.tsx
packages/renderer/src/renderer/screens/OpenGov/Overview/OverviewTreasury.tsx
packages/renderer/src/utils/RenderingUtils.tsx

UI reacts to exceptions and errors.

feat: ui edge cases

---

packages/renderer/src/renderer/screens/Home/Send/Dialogs/DialogRecipient.tsx
packages/renderer/src/renderer/screens/Home/Send/Dialogs/Wrappers.ts
packages/renderer/src/renderer/screens/Home/Send/index.tsx
packages/renderer/src/utils/RenderingUtils.tsx

Disable send screen in offline mode.

feat: send screen offline mode

---

package.json
packages/renderer/package.json
packages/renderer/src/controller/APIsController.ts
packages/renderer/src/controller/dedot/APIsController.ts
packages/renderer/src/model/Api.ts
packages/renderer/src/model/dedot/Api.ts
packages/renderer/tests/APIsController.spec.ts
packages/renderer/tsconfig.json
packages/renderer/vitest.config.ts
packages/types/src/apis.ts
packages/types/src/chains/index.ts
yarn.lock

feat: dedot api model + controller

---

package.json
packages/renderer/src/model/dedot/Api.ts
packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/renderer/contexts/main/Bootstrapping/types.ts
packages/renderer/src/renderer/contexts/main/Chains/defaults.ts
packages/renderer/src/renderer/contexts/main/Chains/index.tsx
packages/renderer/src/renderer/contexts/main/Chains/types.ts
packages/renderer/src/renderer/screens/Home/Footer/RpcSelect.tsx
packages/renderer/src/renderer/screens/Home/Footer/Wrapper.ts
packages/renderer/src/renderer/screens/Home/Footer/index.tsx
yarn.lock

UI added to manage Dedot clients in the main window footer.

feat: dedot chain connections footer ui

---

packages/renderer/src/controller/dedot/APIsController.ts
packages/renderer/src/model/Track.ts
packages/renderer/src/model/dedot/Api.ts
packages/renderer/src/renderer/callbacks/intervaled.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/hooks/useOpenGovMessagePorts.ts
packages/renderer/src/utils/OpenGovUtils.ts
packages/types/src/apis.ts
packages/types/src/openGov.ts

Replace Polkadot.js with Dedot for OpenGov backend.

chore: open gov dedot migration

---

package.json
packages/renderer/src/config/chains.ts
packages/renderer/src/controller/ExtrinsicsController.ts
packages/renderer/src/controller/dedot/APIsController.ts
packages/renderer/src/utils/AccountUtils.ts
packages/types/src/accounts.ts
packages/ui/src/components/QRCode/types.ts
yarn.lock

Replace Polkadot.js with Dedot for extrinsics backend.

chore: dedot extrinsics migration

---

packages/main/src/controller/OnlineStatusController.ts
packages/renderer/src/controller/SubscriptionsController.ts
packages/renderer/src/controller/dedot/APIsController.ts
packages/renderer/src/controller/legacy/APIsController.ts
packages/renderer/src/model/QueryMultiWrapper.ts
packages/renderer/src/model/dedot/Api.ts
packages/renderer/src/model/legacy/Api.ts
packages/renderer/src/orchestrators/TaskOrchestrator.ts
packages/renderer/src/renderer/callbacks/index.ts
packages/renderer/src/renderer/callbacks/nominating.ts
packages/renderer/src/renderer/callbacks/oneshots.ts
packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/renderer/contexts/main/Bootstrapping/types.ts
packages/renderer/src/renderer/contexts/main/Chains/defaults.ts
packages/renderer/src/renderer/contexts/main/Chains/index.tsx
packages/renderer/src/renderer/contexts/main/Chains/types.ts
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/screens/Home/Footer/RpcSelect.tsx
packages/renderer/src/renderer/screens/Home/Footer/index.tsx
packages/renderer/src/utils/AccountUtils.ts
packages/renderer/src/utils/ApiUtils.ts

Replace Polkadot.js with Dedot for chain subscriptions.

chore: dedot subscriptions migration

---

package.json
packages/renderer/package.json
packages/renderer/src/config/chains.ts
packages/renderer/src/controller/EventsController.ts
packages/renderer/src/controller/NotificationsController.ts
packages/renderer/src/controller/dedot/APIsController.ts
packages/renderer/src/controller/dedot/worker.ts
packages/renderer/src/model/QueryMultiWrapper.ts
packages/renderer/src/model/dedot/Api.ts
packages/renderer/src/renderer/callbacks/index.ts
packages/renderer/src/renderer/callbacks/nominating.ts
packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/renderer/contexts/main/Bootstrapping/types.ts
packages/renderer/src/renderer/screens/Home/Footer/RpcSelect.tsx
packages/renderer/src/utils/AccountUtils.ts
packages/renderer/src/utils/OpenGovUtils.ts
packages/renderer/src/utils/TextUtils.ts
packages/types/src/apis.ts
packages/ui/package.json
packages/ui/src/kits/Buttons/index.scss
yarn.lock

Integrate smoldot light client.

feat: light client integration

---

README.md

Attribute Dedot in the README.

chore: readme attributions

---

packages/main/src/controller/WindowsController.ts
packages/preload/src/preload.ts
packages/renderer/src/renderer/screens/Home/index.tsx
packages/ui/src/components/Header/index.tsx
packages/ui/src/components/Header/types.ts
packages/ui/tests/Header.spec.tsx

chore: base window hide behavior

---

packages/main/src/config/main.ts
packages/main/src/controller/SettingsController.ts

chore: tweak default settings

---

package.json
yarn.lock

Bump to latest version of electron-builder.

chore: bump electron-builder

---

package.json
packages/main/package.json
packages/main/src/utils/SystemUtils.ts
packages/renderer/src/renderer/Router.tsx
packages/renderer/src/renderer/screens/Import/Home.tsx
packages/types/package.json
yarn.lock

chore: bump electron to 35.2.1

---

packages/renderer/src/model/QueryMultiWrapper.ts
packages/renderer/src/renderer/callbacks/index.ts
packages/renderer/src/utils/AccountUtils.ts

Fix Westend balances logic to work with network update.

fix: westend balances

---

packages/renderer/src/renderer/screens/Home/Manage/Wrappers.tsx
packages/renderer/src/renderer/screens/Home/Manage/index.tsx
packages/renderer/src/renderer/screens/Home/index.tsx

Fix a scroll issue with the subscriptions carousel. The left and right containers are now scrolled independently.

fix: subscriptions carousel scroll

---

packages/renderer/src/controller/SubscriptionsController.ts
packages/renderer/src/model/QueryMultiWrapper.ts
packages/renderer/src/renderer/callbacks/index.ts
packages/renderer/src/renderer/callbacks/nominating.ts
packages/renderer/src/renderer/callbacks/oneshots.ts
packages/renderer/src/renderer/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/renderer/contexts/main/Subscriptions/index.tsx
packages/renderer/src/renderer/hooks/useMainMessagePorts.ts
packages/renderer/src/renderer/screens/Home/Manage/Accounts.tsx
packages/renderer/src/utils/AccountUtils.ts
packages/renderer/src/utils/ApiUtils.ts
packages/renderer/src/utils/DebugUtils.ts
packages/renderer/src/utils/EventUtils.ts
packages/renderer/src/utils/TextUtils.ts
packages/types/src/subscriptions.ts

Clean up utility source files to improve code clarity and readability.

chore: renderer utils cleanup

---

packages/core/src/callbacks/accounts.ts
packages/core/src/library/AccountsLib/balances.ts

Fix calculating and formatting Westend spendable balances.

fix: westend spendable balance

---

package.json
packages/core/src/callbacks/intervaled.ts
packages/core/src/library/OpenGovLib.ts
yarn.lock

- Bump `dedot` to `0.11.1`
- Bump `@dedot/chaintypes` to `0.102.0`

chore: bump dedot packages

---

packages/core/src/controllers/AccountsController.ts
packages/core/src/controllers/SubscriptionsController.ts
packages/core/src/library/CallbackLib.ts
packages/core/src/model/Account.ts
packages/renderer/src/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/contexts/main/DataBackup/index.tsx
packages/renderer/src/contexts/main/Manage/defaults.ts
packages/renderer/src/contexts/main/Manage/index.tsx
packages/renderer/src/contexts/main/Manage/types.ts
packages/renderer/src/contexts/main/Subscriptions/defaults.ts
packages/renderer/src/contexts/main/Subscriptions/index.tsx
packages/renderer/src/contexts/main/Subscriptions/types.ts
packages/renderer/src/hooks/useMainMessagePorts.ts
packages/renderer/src/screens/Home/Manage/Permissions.tsx
packages/ui/src/utils/toast.tsx

Delegate logic to update React state for tasks in the subscriptions controller, and other cleanups.

chore: core subscription refactors

---

packages/renderer/src/contexts/import/AccountStatuses/index.tsx
packages/renderer/src/contexts/import/ImportHandler/index.tsx
packages/renderer/src/screens/Import/ReadOnly/Dialogs/DialogImportReadOnly.tsx
packages/renderer/src/screens/Import/ReadOnly/Manage.tsx

Implements a dialog for importing read-only accounts, improving UX.

feat: read only accounts import dialog

---

packages/renderer/src/screens/Import/Addresses/Address.tsx
packages/renderer/src/screens/Import/Addresses/Dialogs/DialogShowAddress.tsx
packages/ui/src/components/Hardware/HardwareAddress/HardwareAddress.tsx
packages/ui/src/components/Hardware/HardwareAddress/Wrapper.ts
packages/ui/src/components/Hardware/HardwareAddress/types.ts

Initial encoded address row UI and dialog for showing the full address.

chore: address listing ui iteration

---

packages/main/src/controller/AddressesController.ts
packages/main/src/main.ts
packages/renderer/src/contexts/import/ImportHandler/index.tsx
packages/renderer/src/contexts/import/WalletConnectImport/index.tsx
packages/renderer/src/hooks/useSendNative.ts
packages/renderer/src/screens/Action/Helpers.tsx
packages/renderer/src/screens/Home/Send/Dialogs/DialogRecipient.tsx
packages/renderer/src/screens/Home/Send/Dialogs/types.ts
packages/renderer/src/screens/Home/Send/index.tsx
packages/renderer/src/screens/Import/ReadOnly/Dialogs/DialogImportReadOnly.tsx
packages/renderer/src/screens/Import/Vault/Reader.tsx
packages/types/src/accounts.ts
packages/types/src/communication.ts
packages/ui/src/components/Hardware/HardwareAddress/HardwareAddress.tsx

Refactor send screen accounts to work with new generic account types, along with other fixes and cleanups.

fix: send screen

---

packages/core/src/library/ImportLib.ts
packages/main/src/utils/ImportUtils.ts
packages/renderer/src/screens/Import/Actions/Confirm.tsx
packages/renderer/src/screens/Import/Actions/Delete.tsx
packages/renderer/src/screens/Import/Actions/Remove.tsx
packages/renderer/src/screens/Import/Addresses/Listing.tsx
packages/types/src/accounts.ts
packages/ui/src/components/Hardware/HardwareAddress/HardwareAddress.tsx
packages/ui/src/components/Hardware/HardwareAddress/Wrapper.ts

Remove deprecated account types and cleanup.

chore: remove deprecated code + cleanup

---

packages/renderer/src/contexts/import/RenameHandler/defaults.ts
packages/renderer/src/contexts/import/RenameHandler/index.tsx
packages/renderer/src/contexts/import/RenameHandler/types.ts
packages/renderer/src/screens/Import/Addresses/Dialogs/DialogBulkRename.tsx
packages/renderer/src/screens/Import/Addresses/Dialogs/DialogManageAccounts.tsx
packages/renderer/src/screens/Import/Addresses/Dialogs/DialogRename.tsx
packages/renderer/src/screens/Import/Addresses/Dialogs/DialogShowAddress.tsx
packages/renderer/src/screens/Import/Addresses/Dialogs/NetworkLabel.tsx
packages/renderer/src/screens/Import/Addresses/Dropdowns/DropdownAccount.tsx
packages/renderer/src/screens/Import/Addresses/Listing.tsx
packages/ui/src/components/Hardware/HardwareAddress/HardwareAddress.tsx
packages/ui/src/components/Hardware/HardwareAddress/types.ts

Rename individual accounts via the account dropdown menu `Rename` option.

feat: individual account rename dialog

---

package.json
packages/renderer/src/contexts/main/Bootstrapping/index.tsx
packages/renderer/src/contexts/main/Bootstrapping/worker.ts
yarn.lock

Create the smoldot client using the dedot `startWithWorker` util.

chore: use dedot util for smoldot client 

---

packages/renderer/src/contexts/import/Addresses/defaults.ts
packages/renderer/src/contexts/import/Addresses/index.tsx
packages/renderer/src/contexts/import/Addresses/types.ts
packages/renderer/src/contexts/import/ImportHandler/index.tsx
packages/renderer/src/contexts/import/ImportHandler/types.ts
packages/renderer/src/contexts/import/WalletConnectImport/index.tsx
packages/renderer/src/screens/Import/Ledger/Import/index.tsx
packages/renderer/src/screens/Import/ReadOnly/Dialogs/DialogImportReadOnly.tsx
packages/renderer/src/screens/Import/Vault/Reader.tsx
packages/ui/vite.config.js

fix: debugging

---

packages/renderer/src/screens/Import/Addresses/Listing.tsx
packages/renderer/src/screens/OpenGov/Referenda/Wrappers.ts
packages/renderer/src/screens/OpenGov/Referenda/index.tsx
packages/ui/src/styles/flex.ts

UI tweaks for displaying empty items.

chore: empty items ui tweaks

---

packages/core/src/callbacks/accounts.ts
packages/core/src/library/AccountsLib/balances.ts
packages/main/src/ledger/utils.ts

Fix `free` and `spendable` balance calculations according to the recent runtime balances migration.

fix: balances

---

.github/workflows/release-please.yml

Update release-please workflow.

fix: release please workflow

---

.github/workflows/release-windows.yml
package.json
scripts/electron-builder.config.prod.mjs

Implement workflow for building and publishing the Windows EXE to a tagged release.

feat: windows release workflow

---

packages/core/src/library/TextLib.ts
packages/renderer/src/contexts/main/Addresses/defaults.ts
packages/renderer/src/contexts/main/Addresses/index.tsx
packages/renderer/src/contexts/main/Addresses/types.ts
packages/renderer/src/screens/Home/Send/Dialogs/DialogSelectAccount.tsx
packages/renderer/src/screens/Home/Send/Dialogs/Wrappers.ts
packages/renderer/src/screens/Home/Summary/index.tsx

Display an account source badge in the send screen's account selector dialog.

feat(ui): display source in account selector dialog

---

packages/core/src/controllers/IntervalsController.ts
packages/renderer/src/contexts/main/DataBackup/index.tsx
packages/renderer/src/contexts/main/IntervalTasksManager/index.tsx
packages/renderer/src/hooks/useMainMessagePorts.ts
packages/renderer/src/screens/Home/OpenGov/Subscriptions.tsx

Fixes in the intervals controller.

fix(core): online status and subscriptions checking in intervals controller

---

packages/renderer/src/screens/Home/Events/Item.tsx
packages/renderer/src/screens/Home/Events/Wrappers.tsx

Adds a network icon to event items and UI tweaks.

feat(ui): add network icon to events

---

packages/consts/src/treasury.ts
packages/renderer/src/Providers.tsx
packages/renderer/src/contexts/main/TreasuryApi/defaults.ts
packages/renderer/src/contexts/main/TreasuryApi/index.tsx
packages/renderer/src/contexts/main/TreasuryApi/types.ts
packages/renderer/src/contexts/main/index.ts
packages/renderer/src/contexts/openGov/Treasury/default.ts
packages/renderer/src/contexts/openGov/Treasury/index.tsx
packages/renderer/src/contexts/openGov/Treasury/types.ts
packages/renderer/src/hooks/useMainMessagePorts.ts
packages/renderer/src/screens/OpenGov/Overview/OverviewTreasury.tsx
packages/renderer/src/screens/OpenGov/Wrappers.ts
packages/types/package.json
packages/types/src/treasury.ts
packages/ui/src/components/Cards/TreasuryBalanceCard.styles.ts
packages/ui/src/components/Cards/TreasuryBalanceCard.tsx
packages/ui/src/components/Cards/TreasuryStatCard.styles.ts
packages/ui/src/components/Cards/index.ts
packages/ui/src/components/Cards/types.ts
packages/ui/src/components/Cards/utils.ts
packages/ui/src/styles/grid.ts

Renders asset balances in the Polkadot Hub treasury account, including DOT, USDC and USDT, in the OpenGov treasury overview UI.

feat(ui): polkadot asset hub treasury balances

---

packages/renderer/src/screens/Action/Dialogs/Wrappers.ts
packages/renderer/src/screens/Home/Events/Dropdowns/DropdownActions.tsx
packages/renderer/src/screens/Home/Footer/Wrapper.ts
packages/renderer/src/screens/Home/Footer/index.tsx
packages/renderer/src/screens/Home/Manage/Wrappers.tsx
packages/renderer/src/screens/Home/Send/SendHelpers.tsx
packages/renderer/src/screens/Home/Send/index.tsx
packages/renderer/src/screens/Home/Summary/Wrappers.tsx
packages/renderer/src/screens/Import/Addresses/Dialogs/Wrappers.ts
packages/renderer/src/screens/OpenGov/Dropdowns/Wrappers.ts
packages/renderer/src/screens/OpenGov/Referenda/Wrappers.ts
packages/renderer/src/screens/OpenGov/Wrappers.ts
packages/renderer/src/screens/Tabs/ResizeToggles.styles.ts
packages/renderer/src/screens/Tabs/Wrappers.tsx
packages/renderer/src/theme/theme.scss
packages/renderer/src/theme/variables.ts
packages/ui/src/components/AccordionRx/Wrappers.ts
packages/ui/src/components/Cards/TreasuryBalanceCard.styles.ts
packages/ui/src/components/Cards/TreasuryStatCard.styles.ts
packages/ui/src/components/Cards/utils.ts
packages/ui/src/components/Help/Wrappers.ts
packages/ui/src/components/SideNav/SideNav.styles.ts
packages/ui/src/components/Stats/Stats.styles.ts
packages/ui/src/components/TooltipRx/TooltipRx.styles.ts
packages/ui/src/styles/dialog.ts
packages/ui/src/styles/dropdown.ts

chore(ui): polish light theme

---

packages/core/src/controllers/EventsController.ts

Fix URLs to the staking dashboard.

fix(events): staking dashboard urls

---

packages/core/src/controllers/EventsController.ts
packages/core/src/library/AccountsLib/utils.ts
packages/core/src/model/QueryMultiWrapper.ts
packages/main/src/controller/EventsController.ts
packages/renderer/src/contexts/main/DataBackup/index.tsx
packages/renderer/src/hooks/useMainMessagePorts.ts

Fixes account name syncing for managed subscription tasks when renaming accounts, and importing from a data file.

fix(core): account name syncing

---

packages/consts/src/chains.ts
packages/core/src/controllers/ExtrinsicsController.ts
packages/renderer/src/hooks/useSendNative.ts
packages/renderer/src/screens/Home/Send/index.tsx
packages/renderer/src/theme/theme.scss
packages/renderer/src/theme/variables.ts
packages/ui/src/components/Header/Wrapper.ts
packages/ui/src/components/Header/index.tsx

feat(core): pre-release setup

---

README.md
release-please-config.json

Updates the documentation portal link in the readme.

chore(readme): update readme
